### ISSUE TITLE
No tests found

### ISSUE THREAD

**Issue by aignatenko88** [EnricoMi/publish-unit-test-result-action#107]
"No tests found" after running tests with bin/phpunit. I get the following result without details:
![image](https://user-images.githubusercontent.com/39911023/114159346-5d6e7f00-992e-11eb-9dac-2888d320598c.png)

**Comment by EnricoMi** [comment]
Which version are you running? This looks like issue #91.

**Comment by aignatenko88** [comment]
I'm using @v1. Should I try @v1.11?

**Comment by EnricoMi** [comment]
Version @v1 is great, it is always the latest. It should include the fix for #91. Can you point me to the workflow run, if it is public?

**Comment by aignatenko88** [comment]
Unfortunately it's private.
Basically I run the following in docker container:
`php -d memory_limit=-1 bin/phpunit --log-junit tests/test_report.xml`
tests directory is bind mounted to the host.

**Comment by EnricoMi** [comment]
Can you provide me with an example `tests/test_report.xml` so I can reproduce the output locally?

**Comment by aignatenko88** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="Project Test Suite" tests="108" assertions="229" errors="0" warnings="0" failures="0" skipped="3" time="12.299158">
    <testsuite name="someSuite" file="somepath" tests="11" assertions="36" errors="0" warnings="0" failures="0" skipped="0" time="2.178895">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="34" assertions="3" time="0.321590"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="65" assertions="4" time="0.321319"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="116" assertions="3" time="0.085157"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="148" assertions="4" time="0.247534"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="201" assertions="5" time="0.276220"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="263" assertions="3" time="0.088102"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="283" assertions="2" time="0.228568"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="311" assertions="3" time="0.084209"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="336" assertions="2" time="0.218242"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="369" assertions="3" time="0.086126"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="394" assertions="4" time="0.221828"/>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="11" assertions="26" errors="0" warnings="0" failures="0" skipped="0" time="2.198742">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="40" assertions="2" time="0.088170"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="72" assertions="3" time="0.355635"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="149" assertions="2" time="0.095574"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="192" assertions="3" time="0.295335"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="262" assertions="3" time="0.316573"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="336" assertions="2" time="0.111672"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="359" assertions="2" time="0.240297"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="389" assertions="2" time="0.116564"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="418" assertions="2" time="0.232674"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="454" assertions="2" time="0.093316"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="483" assertions="3" time="0.252932"/>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="12" assertions="27" errors="0" warnings="0" failures="0" skipped="0" time="2.052356">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="31" assertions="2" time="0.101939"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="52" assertions="2" time="0.238206"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="80" assertions="2" time="0.106251"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="106" assertions="2" time="0.204812"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="139" assertions="2" time="0.052449"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="164" assertions="2" time="0.274914"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="208" assertions="2" time="0.084105"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="241" assertions="3" time="0.298174"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="296" assertions="2" time="0.107368"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="322" assertions="3" time="0.232611"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="365" assertions="2" time="0.094746"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="396" assertions="3" time="0.256781"/>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="6" assertions="13" errors="0" warnings="0" failures="0" skipped="0" time="1.065537">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="32" assertions="2" time="0.084383"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="53" assertions="2" time="0.262644"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="81" assertions="2" time="0.098420"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="107" assertions="2" time="0.278615"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="140" assertions="2" time="0.095594"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="166" assertions="3" time="0.245881"/>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="2" assertions="4" errors="0" warnings="0" failures="0" skipped="0" time="0.232337">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="41" assertions="2" time="0.107041"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="76" assertions="2" time="0.125296"/>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="2" assertions="4" errors="0" warnings="0" failures="0" skipped="0" time="0.193444">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="43" assertions="2" time="0.093688"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="78" assertions="2" time="0.099756"/>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="5" assertions="12" errors="0" warnings="0" failures="0" skipped="0" time="0.687970">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="28" assertions="2" time="0.062080"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="65" assertions="3" time="0.441262"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="105" assertions="2" time="0.057497"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="142" assertions="3" time="0.067245"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="180" assertions="2" time="0.059886"/>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="1" assertions="2" errors="0" warnings="0" failures="0" skipped="0" time="0.021284">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="31" assertions="2" time="0.021284"/>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="4" assertions="2" errors="0" warnings="0" failures="0" skipped="2" time="0.232812">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="62" assertions="1" time="0.117033"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="86" assertions="1" time="0.076142"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="125" assertions="0" time="0.019800">
        <skipped/>
      </testcase>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="130" assertions="0" time="0.019837">
        <skipped/>
      </testcase>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="1" assertions="1" errors="0" warnings="0" failures="0" skipped="0" time="0.010194">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="10" assertions="1" time="0.010194"/>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="5" assertions="9" errors="0" warnings="0" failures="0" skipped="0" time="0.892217">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="20" assertions="1" time="0.010188"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="30" assertions="1" time="0.183873"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="49" assertions="3" time="0.329161"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="88" assertions="1" time="0.176161"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="110" assertions="3" time="0.192834"/>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="4" assertions="6" errors="0" warnings="0" failures="0" skipped="0" time="0.006609">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="26" assertions="2" time="0.002664"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="37" assertions="1" time="0.001624"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="44" assertions="2" time="0.001177"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="54" assertions="1" time="0.001144"/>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="4" assertions="4" errors="0" warnings="0" failures="0" skipped="0" time="0.295562">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="60" assertions="1" time="0.072680"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="70" assertions="1" time="0.079004"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="89" assertions="1" time="0.073749"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="124" assertions="1" time="0.070129"/>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="3" assertions="3" errors="0" warnings="0" failures="0" skipped="0" time="0.234017">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="61" assertions="1" time="0.066044"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="71" assertions="1" time="0.101249"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="87" assertions="1" time="0.066724"/>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="4" assertions="4" errors="0" warnings="0" failures="0" skipped="0" time="0.220127">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="45" assertions="1" time="0.055882"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="77" assertions="1" time="0.054543"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="103" assertions="1" time="0.053601"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="138" assertions="1" time="0.056101"/>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="10" assertions="11" errors="0" warnings="0" failures="0" skipped="1" time="0.846624">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="67" assertions="1" time="0.132443"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="92" assertions="1" time="0.090502"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="120" assertions="1" time="0.097337"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="159" assertions="2" time="0.052990"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="174" assertions="1" time="0.056706"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="184" assertions="1" time="0.087810"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="219" assertions="2" time="0.119568"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="279" assertions="0" time="0.054629">
        <skipped/>
      </testcase>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="325" assertions="1" time="0.094717"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="362" assertions="1" time="0.059922"/>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="3" assertions="8" errors="0" warnings="0" failures="0" skipped="0" time="0.033990">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="60" assertions="1" time="0.011173"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="83" assertions="5" time="0.014390"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="118" assertions="2" time="0.008427"/>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="7" assertions="11" errors="0" warnings="0" failures="0" skipped="0" time="0.157860">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="46" assertions="2" time="0.015113"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="62" assertions="1" time="0.040619"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="73" assertions="2" time="0.036586"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="85" assertions="1" time="0.011676"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="110" assertions="3" time="0.037995"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="126" assertions="1" time="0.014729"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="141" assertions="1" time="0.001142"/>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="1" assertions="1" errors="0" warnings="0" failures="0" skipped="0" time="0.053216">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="26" assertions="1" time="0.053216"/>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="2" assertions="2" errors="0" warnings="0" failures="0" skipped="0" time="0.122822">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="54" assertions="1" time="0.061487"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="67" assertions="1" time="0.061335"/>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="4" assertions="10" errors="0" warnings="0" failures="0" skipped="0" time="0.314303">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="61" assertions="2" time="0.105383"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="98" assertions="2" time="0.074256"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="135" assertions="3" time="0.064140"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="187" assertions="3" time="0.070524"/>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="3" assertions="3" errors="0" warnings="0" failures="0" skipped="0" time="0.145803">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="41" assertions="1" time="0.048577"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="66" assertions="1" time="0.046942"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="94" assertions="1" time="0.050284"/>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="2" assertions="29" errors="0" warnings="0" failures="0" skipped="0" time="0.016282">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="55" assertions="28" time="0.014037"/>
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="70" assertions="1" time="0.002245"/>
    </testsuite>
    <testsuite name="someSuite" file="somepath" tests="1" assertions="1" errors="0" warnings="0" failures="0" skipped="0" time="0.086154">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="32" assertions="1" time="0.086154"/>
    </testsuite>
  </testsuite>
</testsuites>
`
I replaced real names with dummy data

**Comment by EnricoMi** [comment]
I see the following issues with your `test_report.xml`:

There are `<testsuite>` tags embedded in `<testsuite>` tags:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="Project Test Suite" tests="108" assertions="229" errors="0" warnings="0" failures="0" skipped="3" time="12.299158">
    <testsuite name="someSuite" file="somepath" tests="11" assertions="36" errors="0" warnings="0" failures="0" skipped="0" time="2.178895">
      <testcase name="someName" class="someName" classname="someName" file="/somepath" line="34" assertions="3" time="0.321590"/>
    </testsuite>
  </testsuite>
</testsuites>
```

Second, there is another XML file at the end of the xml file:
```xml
    </testsuite>
  </testsuite>
</testsuites>


<?xml version="1.0" encoding="UTF-8"?> <testsuites>...
```

Can you please investigate if this is exactly what is been given to the publish action?

**Comment by sunshowers** [comment]
JUnit does support nested testsuites just FYI, see the XSD here which says that nested testsuites are supported: https://llg.cubic.org/docs/junit/

**Comment by aignatenko88** [comment]
@EnricoMi yes, I've copied the xml as is after test run

**Comment by EnricoMi** [comment]
> JUnit does support nested testsuites just FYI

Thanks for the pointer. Then I will have to work around that.

**Comment by EnricoMi** [comment]
@aignatenko88 that is definitively an invalid XML file. The second part is an exact copy of the first, so it does not look like two test runs writing to the same file.

I can fix the <testsuite> embedded in <testsuite> tags, but I can fix the invalid XML file issue.

**Comment by EnricoMi** [comment]
@aignatenko88 merged the fix into master, can you give it a try?

        uses: EnricoMi/publish-unit-test-result-action@master

**Comment by aignatenko88** [comment]
Thank you @EnricoMi . @master with Still no luck :(
![image](https://user-images.githubusercontent.com/39911023/114836709-9cdc1600-9ddb-11eb-919c-e8fe2d31611d.png)
![image](https://user-images.githubusercontent.com/39911023/114836472-5f778880-9ddb-11eb-999b-f5995258794f.png)
Also you were right about broken xml. Attaching updated one
[test_report_updated.zip](https://github.com/EnricoMi/publish-unit-test-result-action/files/6316236/test_report_updated.zip)

**Comment by EnricoMi** [comment]
Sorry, my bad. The master branch has to be tested like this:

    uses: EnricoMi/publish-unit-test-result-action/composite@master

**Comment by EnricoMi** [comment]
> Attaching updated one: [test_report_updated.zip](https://github.com/EnricoMi/publish-unit-test-result-action/files/6316236/test_report_updated.zip)

This test result file is a valid XML file. So I am optimistic the problem was only the `<testcase>` embedded in `<testcase>`.

**Comment by EnricoMi** [comment]
This has been released and is now available via `@v1`.

**Comment by aignatenko88** [comment]
Thanks @EnricoMi 
Now I get the following results

**Comment by EnricoMi** [comment]
There is only a link to test results if there are failures. This looks all as expected.
