### ISSUE TITLE
Disable comparisons to earlier test runs?

### ISSUE THREAD

**Issue by sunshowers** [EnricoMi/publish-unit-test-result-action#115]
Hey, thanks for writing this lovely action!

I'm trying to integrate it into our work project and I'm running into a specific issue around comparisons with earlier commits: the action does a good job doing so, but I'd love a way to disable those comparisons.

The reason we need to do that is that we have some smarts built into our test runner which only runs a subset of tests based on which parts of the codebase were changed. So the number of tests run varies wildly from commit to commit.

Alternatively, we could potentially provide the baseline in some format (e.g. in the JUnit format as skipped tests). If that works, it should be possible to provide better data as well -- e.g. if a test gets added and another gets removed, you'd able to say "+1, -1".

What do you think?

**Comment by EnricoMi** [comment]
Hi, thanks for using this action!

I can see that this is a valid situation where you don't want to compare to earlier commits as numbers become meaningless. That should be easy to add.

However, especially in your situation of partial testing, identifying tests that are accidentally removed or skipped becomes crucial. I like the idea of some kind of baseline. What I could think of is to fetch the test result files from the target branch (the commit we compare PRs against) and then have the unit tests overwrite them. This way, the action could compare results as is. Except for where suites are being removed, it should be able to identify all changes.

**Comment by sunshowers** [comment]
> I can see that this is a valid situation where you don't want to compare to earlier commits as numbers become meaningless. That should be easy to add.

That would be great. I have a simple implementation for just the check bit in my fork at https://github.com/sunshowers/publish-unit-test-result-action/commit/3261e64e3dd674c1296bd2a42ee19b3499011c87 -- I haven't thought too much about a good UI but wanted to share this.

> However, especially in your situation of partial testing, identifying tests that are accidentally removed or skipped becomes crucial. I like the idea of some kind of baseline. What I could think of is to fetch the test result files from the target branch (the commit we compare PRs against) and then have the unit tests overwrite them.

Oh that sounds like an interesting plan: kind of maintaining the baseline state and overwriting it incrementally as necessary. I'm not sure if we can put that specific plan into practice though: this would add a dependency to our test 

Regardless, I'm coming to realize that we'll need to make some fairly extensive customizations to the action to meet our needs, so I may end up building this out in a way that works for us. I think the way we'll probably do it is publish a baseline artifact with a list of tests in the same JUnit format, then use that as the input to perform the diff against. Happy to talk about upstreaming that implementation once it's done, or just maintaining a patchset of our changes ourselves.

**Comment by EnricoMi** [comment]
I have merged the configuration bit to master, please give it a try:

    uses: EnricoMi/publish-unit-test-result-action@master

I'd be happy to see how you have solved the baseline bit. Just open a new issue and we can talk about your use case and experience there. Thanks for raising this.

**Comment by EnricoMi** [comment]
This has been released and is now available via `@v1`.
