### ISSUE TITLE
v1.13 regression causing action to run infinitely

### ISSUE THREAD

**Issue by bb1950328** [EnricoMi/publish-unit-test-result-action#124]
In [this](https://github.com/bb1950328/BrickSim/actions/runs/804889273) run, the "Publish Catch2 Test Results" action runs until the timeout of 6 hours. 
In [this](https://github.com/bb1950328/BrickSim/actions/runs/804944960) run, I set the version back to `1.12` and the action behaves correctly.

The stacktrace suggests that there's an infinite loop when crawling files: 
```python
Traceback (most recent call last):
  File "/action/publish_unit_test_results.py", line 212, in <module>
    main(settings)
  File "/action/publish_unit_test_results.py", line 65, in main
    files = get_files(settings.files_glob)
  File "/action/publish_unit_test_results.py", line 47, in get_files
    for files_glob in multiline_files_globs
  File "/action/publish_unit_test_results.py", line 48, in <setcomp>
    for file in glob(files_glob[1:], recursive=True)
  File "/usr/local/lib/python3.6/glob.py", line 20, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/usr/local/lib/python3.6/glob.py", line 71, in _iglob
    for dirname in dirs:
  File "/usr/local/lib/python3.6/glob.py", line 72, in _iglob
    for name in glob_in_dir(dirname, basename, dironly):
  File "/usr/local/lib/python3.6/glob.py", line 110, in _glob2
    yield from _rlistdir(dirname, dironly)
  File "/usr/local/lib/python3.6/glob.py", line 138, in _rlistdir
    for y in _rlistdir(path, dironly):
  File "/usr/local/lib/python3.6/glob.py", line 138, in _rlistdir
    for y in _rlistdir(path, dironly):
  File "/usr/local/lib/python3.6/glob.py", line 138, in _rlistdir
    for y in _rlistdir(path, dironly):
  [Previous line repeated 13 more times]
  File "/usr/local/lib/python3.6/glob.py", line 139, in _rlistdir
    yield os.path.join(x, y)
KeyboardInterrupt
```

Relevant section of my workflow yml:
```yml
- name: Publish Unit Test Results
  uses: EnricoMi/publish-unit-test-result-action@v1.12
  with:
    files: ./**/*.xml
    check_name: Catch2 Test Results
    comment_title: Catch2 Test Results
```

**Comment by EnricoMi** [comment]
Thank you very much for raising this issue. I have reverted that feature and released v1.14. I will investigate that and add some more test cases.

**Comment by bb1950328** [comment]
Thank you for your very fast response. I can confirm that v1.14 [works correctly](https://github.com/bb1950328/BrickSim/runs/2488173691?check_suite_focus=true).

**Comment by EnricoMi** [comment]
I have fixed the feature and released a new version. Please give it a try.

The problem was that the pattern was turned into `/**/*.xml`, which 1) iterates through the entire filesystem and 2) there are some symmetric link cycles, which explodes the number of visited paths.

Thanks for raising this so quickly. I hope everything works smooth with file patterns now.

**Comment by bb1950328** [comment]
[v1.15 works](https://github.com/bb1950328/BrickSim/runs/2490997733?check_suite_focus=true).
Thank you very much for fixing this so quickly.

**Comment by EnricoMi** [comment]
Thanks again for the quick and detailed bug report. Sorry for the disruption.
