### ISSUE TITLE
Add tooltip and documentation link to icons

### ISSUE THREAD

**Issue by igagis** [EnricoMi/publish-unit-test-result-action#142]
For example, the summary looks like this:

![image](https://user-images.githubusercontent.com/783401/122942616-0437b880-d37f-11eb-9b99-4375c7d702b4.png)

It is not very clear what those icons mean. Would be nice if when hovering the icon with mouse cursor there would be a tip saying that, for example the fire icon means "errored" test cases, zzZ icon means "skipped" test cases etc.

**Comment by EnricoMi** [comment]
Good idea, but is that even possible with GitHub Markdown?

**Comment by igagis** [comment]
Ah, I didn't realize that those icons are emojis...

The only way found to make this in markdown is as follows:
```
This is a [:fire:](## "fire") example.
```

This is a [:fire:](## "fire") example.

**Comment by EnricoMi** [comment]
This is a good idea. I would prefer to link to the [README.md](https://github.com/EnricoMi/publish-unit-test-result-action#readme), which lists all icons next to a description. Do you know if there is a way to do both, have an alt text *and* a link?

**Comment by igagis** [comment]
Perhaps, give the link a descriptive name:

```
This is a [:fire:](## "README.md#failed-tests") example.
```

This is a [:fire:](## "README.md#failed-tests") example.

**Comment by EnricoMi** [comment]
Markdown supports a link and a tooltip:

## Unit Test Results (Dockerfile)
     11 files  ±0       11 suites  ±0   23s :stopwatch: ±0s
   235 tests ±0     235 [:heavy_check_mark:](https://github.com/EnricoMi/publish-unit-test-result-action/blob/master/README.md "passed tests") ±0    0 [:zzz:](https://github.com/EnricoMi/publish-unit-test-result-action/blob/master/README.md "skipped / disabled tests") ±0  0 [:x:](https://github.com/EnricoMi/publish-unit-test-result-action/blob/master/README.md "failed tests") ±0 
2 585 runs  ±0  2 573 [:heavy_check_mark:](https://github.com/EnricoMi/publish-unit-test-result-action/blob/master/README.md "passed tests") ±0  12 [:zzz:](https://github.com/EnricoMi/publish-unit-test-result-action/blob/master/README.md "skipped / disabled tests") ±0  0 [:x:](https://github.com/EnricoMi/publish-unit-test-result-action/blob/master/README.md "failed tests") ±0 

I am going to add those tooltips and links to the action.
