### ISSUE TITLE
redundant info added to github actions repot

### ISSUE THREAD

**Issue by igagis** [EnricoMi/publish-unit-test-result-action#145]
Currently the report for failed test looks like:

![image](https://user-images.githubusercontent.com/783401/122945329-2fbba280-d381-11eb-8f54-96989768d880.png)

the whole line with github octocat icon (and `guthub-actions / test report: linux - debian:buster`) is redundant since it repeats the name of the job selected on the left, as seen from the screenshot. And this line is duplicated for each failed test. Just a waste of screen space. Remove that line.

**Comment by EnricoMi** [comment]
That line is added by GitHub, the publish-unit-test-result-action has no control over it.

The action only has control over the content of these two lines in your example above: `test_which_fails_check_eq_with_custom_message failed` and `test/failed/junit.xml`. And even for these only control over the content, not the color or text formatting.

GitHub is very restrictive when it comes to controlling the action outputs.
