### ISSUE TITLE
Action is failing due to secondary rate limit warning

### ISSUE THREAD

**Issue by berndku** [EnricoMi/publish-unit-test-result-action#170]
The action is randomly failing due to [secondary rate limit](https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits) errors. 

**Observed Error:** 

`github.GithubException.RateLimitExceededException: 403 {"documentation_url": "https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#secondary-rate-limits", "message": "You have exceeded a secondary rate limit. Please wait a few minutes before you try again."}`

(happens after 2s of execution)

**The action is invoked like this:**

Run EnricoMi/publish-unit-test-result-action@v1
  with:
    check_name:  Results
    comment_title: Results
    files: ./junit.xml
    github_token: ***
    github_retries: 10
    fail_on: test failures
    hide_comments: all but latest
    comment_mode: update last
    compare_to_earlier_commit: true
    pull_request_build: merge
    check_run_annotations: all tests, skipped tests
    seconds_between_github_reads: 0.25
    seconds_between_github_writes: 2.0

**Stack Trace**

Traceback (most recent call last):
  File "/action/publish_unit_test_results.py", line 283, in <module>
    main(settings, gha)
  File "/action/publish_unit_test_results.py", line 96, in main
    Publisher(settings, gh, gha).publish(stats, results.case_results, conclusion)
  File "/action/publish/publisher.py", line 66, in publish
    pull = self.get_pull(self._settings.commit)
  File "/action/publish/publisher.py", line 82, in get_pull
    logger.debug(f'found {issues.totalCount} pull requests in repo {self._settings.repo} for commit {commit}')
  File "/usr/local/lib/python3.6/site-packages/github/PaginatedList.py", line 150, in totalCount
    "GET", self.__firstUrl, parameters=params, headers=self.__headers
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 355, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"documentation_url": "https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#secondary-rate-limits", "message": "You have exceeded a secondary rate limit. Please wait a few minutes before you try again."}

**Comment by EnricoMi** [comment]
Can you provide me a link to such a workflow run if the repo is public? Can you set `ROOT_LOG_LEVEL` and `LOG_LEVEL` to `DEBUG` to get some extra insights?

**Comment by berndku** [comment]
Unfortunately the workflows are all private. I will work on a trace with DEBUG enabled. This may take a few days. 

Since the issue happens after 2s, it may be related to retry-behavior of 403. We checked the primary rate limit for the GITHUB_TOKEN and it is way under the 15K limit (using GHEC).

**Comment by EnricoMi** [comment]
The latest release does not retry 403 responses at all, retrying those is sitting unreleased in master. I am wondering which API access might trigger this.

**Comment by berndku** [comment]
It seems the retry for 403 has been released now. We´ll try the new version and re-open the issue if the error occurs again.
