### ISSUE TITLE
JUnit: No annotation with failure details

### ISSUE THREAD

**Issue by fabioknoedt** [EnricoMi/publish-unit-test-result-action#171]
> Each failing test will produce an annotation with failure details: 

No annotation/comment is being created with more information about the failed test.
The summary comment is created with no issue but without information about what test failed.

That's the only comment I get:
<img width="637" alt="image" src="https://user-images.githubusercontent.com/14126548/134502380-eb293e04-b785-46ef-a4f0-63e2a9fe49d5.png">

My setup is PHPUnit generating a `junit.xml` file.

Is this behaviour expected or is it a bug? Thanks!

**Comment by EnricoMi** [comment]
Have you clicked on the `see this check` link? That is the place where GitHub displays annotations.

**Comment by fabioknoedt** [comment]
@EnricoMi hey, I did click but I was in the Github iOS app which throws a “Something went wrong” - I just tested using the website and it shows the annotation. I was expecting to be a comment in the PR though, that’s why I didn’t bother to try elsewhere. Thanks!
