### ISSUE TITLE
Feature Request, Coverage Badge/Shield

### ISSUE THREAD

**Issue by Bwen** [EnricoMi/publish-unit-test-result-action#178]
I am not 100% if this is even doable, but it would be nice to be able to refer to the last action for coverage % and add some Markdown (_manually_) in the `README.md` that always points to the latest for main branch.

For the PR we could add that Badge/Shield to the PR comment for current build.

I believe img.shields.io can create custom shields on the fly :thinking:

**Comment by EnricoMi** [comment]
And how does this coverage relate to this GitHub action? This action does not know about any metrics that would allow for computing the coverage.

**Comment by Bwen** [comment]
it could accept another test report format that do have the information? :sweat_smile:

**Comment by EnricoMi** [comment]
It could, though this looks a bit out of scope. Any extending contribution welcome.
