### ISSUE TITLE
Test results are attributed to the wrong workflow

### ISSUE THREAD

**Issue by TWiStErRob** [EnricoMi/publish-unit-test-result-action#181]
My workflow setup: https://github.com/TWiStErRob/net.twisterrob.healthcheck/tree/master/.github/workflows
 * CI uses tests-run.yml (All and Smoke tests)
 * Schedule uses tests-run.yml (cinema, regex, www, uw tests)
 * tests-run.yml uses EnricoMi/publish-unit-test-result-action@v1

Which means that each result should be under the corresponding workflow that uses test-run.yml, but all of them are under CI:
https://github.com/TWiStErRob/net.twisterrob.healthcheck/pull/9
![image](https://user-images.githubusercontent.com/2906988/139578542-b04c7912-61a8-485d-bab7-36c603360e4b.png)

or earlier in another commit it was all under Scheduled (since then I renamed the jobs):
![image](https://user-images.githubusercontent.com/2906988/139578628-edfef237-a75a-47f7-ba2c-46ff031acdf8.png)

**Comment by EnricoMi** [comment]
This is a known limitation of the GitHub Check Status API. GitHub attributes the Check Status to an arbitrary workflow, not the one that is running the action that calls the Check Status API. This is annoying, I know. See #12.

**Comment by TWiStErRob** [comment]
Wow, that's quite a non-response from GitHub. Thanks, hope there will be something happening. I'll submit a support request too to get it on their radar more.
For ref: https://github.community/t/specify-check-suite-when-creating-a-checkrun/118380/16

**Comment by TWiStErRob** [comment]
Trimmed down version of their response, sounds more promising than is visible at github.community:
> We have had a number of users write in about this and the team is currently working on improving this behavior.
> Currently, there isn't any public issue available for tracking. We have internal discussions taking place with our developers to form a solution to this problem. I have added your report to it for tracking.
> While I do not have an ETA for exactly when we'll see changes made, I can assure you there's been much activity on this issue recently.
> We usually announce new features as they become available on the [ChangeLog page](https://github.blog/changelog/) of our Blog. You can keep an eye on these for when it becomes available.

**Comment by TWiStErRob** [comment]
I guess this is the same issue: but with timings days apart.

I have a failed scheduled nightly workflow run
https://github.com/TWiStErRob/net.twisterrob.healthcheck/actions/runs/1415459852

With a failed test in a job
https://github.com/TWiStErRob/net.twisterrob.healthcheck/runs/4089035369

Which reports its annotations to the CI run of the last commit on master.
https://github.com/TWiStErRob/net.twisterrob.healthcheck/runs/4089052737

The consequence of this is that I can't see the failed test info on the scheduled run until I click around and find the last master commit's annotations.

**Comment by remcowesterhoud** [comment]
I'm running into this issue now. Did anyone ever find a solution for this? It seems GitHub still didn't do anything about this limitation.

**Comment by EnricoMi** [comment]
The best workaround that community has come up with is https://github.com/orgs/community/discussions/24616#discussioncomment-5607870.
