### ISSUE TITLE
We don't seem to get detail on test results?

### ISSUE THREAD

**Issue by max-sixty** [EnricoMi/publish-unit-test-result-action#183]
I really liked the idea of this aciton, and added it to xarray.

Unfortunately — unless I'm missing it — we don't seem to be getting one of the big benefits of this: immediate detail on what failed in tests.

If we're doing something wrong in our configs, I'd love to know.

ref https://github.com/pydata/xarray/pull/5946

Thank you!

**Comment by EnricoMi** [comment]
Sure, can you point me to the commit that has test failures? Then I can have a look what went wrong.

**Comment by max-sixty** [comment]
Thanks a lot @EnricoMi !

Here's an example: https://github.com/pydata/xarray/pull/5873

I see there that there are no test failures reported in the comment. So possibly our config is incorrect. I thought I copied it from your (very clear) readme, but it's likely I made a mistake. I just had another look but can't see what — if you spot anything then greatly appreciated.

**Comment by EnricoMi** [comment]
Yeah, found another one: https://github.com/pydata/xarray/pull/5734

The comment got overwritten by a later run, which had no test failures. Check the third last edit of the comment:
![image](https://user-images.githubusercontent.com/44700269/140623627-4dca2843-30eb-47c4-b912-35fcfb8b34fe.png)

![image](https://user-images.githubusercontent.com/44700269/140623377-c9b874aa-a108-4bd9-9b4a-293beff0b627.png)

It links a check, and that one should contain some failures, but it does not: https://github.com/pydata/xarray/runs/4122341392

The log of the respective action runs does not show any problems:
https://github.com/pydata/xarray/runs/4122335672?check_suite_focus=true#step:4:18

The strange thing it is that it creates multiple annotations (as can be seen in the log), but there are only 4 annotations. The first annotation says `13454 to 14159`, clearly all earlier annotations got lost. The first annotation would be the failure.

So the GitHub API somehow swallows some annotations. This is not good.

![image](https://user-images.githubusercontent.com/44700269/140623515-af109b5e-aebb-49be-8f8a-82fab64e0728.png)

**Comment by EnricoMi** [comment]
In your example, the comment also got overwritten by a later run, the second last edit has a failure:
![image](https://user-images.githubusercontent.com/44700269/140623659-53c32664-5ad5-4ae1-8e0b-df4ecd4a1e30.png)
It links to this check: https://github.com/pydata/xarray/runs/3941131935
And that one has failure annotations:
![image](https://user-images.githubusercontent.com/44700269/140623673-63e25517-0a9b-4631-b65a-0ff1d9ca4537.png)

That check has all annotations.

**Comment by EnricoMi** [comment]
@max-sixty your setup looks good, it looks like an issue with the GitHub API. However, I recommend to use the latest setup: https://github.com/pydata/xarray/pull/5947

**Comment by max-sixty** [comment]
@EnricoMi thank you so much! Let's give this a whirl!

**Comment by EnricoMi** [comment]
I reckon this is a transient issue with GitHub API. Lets monitor the annotations for a while if we see more instances where some are missing (for commits with and without failures).

**Comment by EnricoMi** [comment]
@max-sixty I have looked through a few dozens of check results in your project and all have the expected annotations. If you spot one run that produces incomplete annotations, simply rerun the publish workflow. This can be done without rerunning the tests themself as the workflows are separated. If this occurs too frequently, then this issue becomes reproducible and we could do some debugging.

**Comment by max-sixty** [comment]
Great! Thanks a lot @EnricoMi ! I'll close this for now and reopen if we see this again, if that works for you.

**Comment by EnricoMi** [comment]
@max-sixty I think I have found the issue may explain your observation: #215 When there are more than 50 annotations (test failures, test name list, ...) than only the last modulo 50 annotations appear. It is now clear how this happened, and it is fixed in master. I am about to release a new version.
