### ISSUE TITLE
Parsing for &gt; and such in test output

### ISSUE THREAD

**Issue by kvanbere** [EnricoMi/publish-unit-test-result-action#184]
I have some tests that, when run, produce the following detail lines in the `xml`:
```
TestName (TestSuiteName &gt; ParticularTestSuite) failed 
```

These are generated by MATLAB and pushed to GH as-is by this action.
I think that perhaps, before pushing to the GitHub API, it would be nice if the control characters could be unencoded so that the output is prettier.

**Comment by EnricoMi** [comment]
You are right, such XML entities should get resolved before sending them to the GitHub API. I think this should be done by the used JUnit parsig library `junitparser`, which in turn uses the Python XML API.

I am looking into how to fix this and where to fix this best.

**Comment by EnricoMi** [comment]
This is explicitly done by the used junitparser lib, though this design decision is questionable. I have raised https://github.com/weiwei/junitparser/issues/71 to elaborate on this decision. With #185, this "feature" is circumvented so the publish action shows the expected behaviour.

Thanks for raising this.

**Comment by kvanbere** [comment]
Wow, well done! You guys don't muck around 😄

**Comment by EnricoMi** [comment]
Merged into master. Please test with

    uses: EnricoMi/publish-unit-test-result-action/composite@master

**Comment by kvanbere** [comment]
Looks good, thanks! Is it possible to get an immutable `@tag` for a release that has this feature, but not `master`?

**Comment by kvanbere** [comment]
You guys don't have a way to tip you a coffee or anything like that in the README.

**Comment by kvanbere** [comment]
You guys don't have a way to tip you a coffee or anything like that in the README.

**Comment by EnricoMi** [comment]
There will be a release soon. I recommend to use tag `@v1`, which is not immutable but will point to the latest (non-breaking) version. And for the tip: you are welcome, just spread the word and use this action where ever you can.

**Comment by EnricoMi** [comment]
Just released as `v1.24`.
