### ISSUE TITLE
Container action is only supported on Linux

### ISSUE THREAD

**Issue by slavafomin** [EnricoMi/publish-unit-test-result-action#190]
Hello!

Thank you for this great tool!

However, it seems that it's not actually working on Windows and MacOS, I'm getting the following error:

```console
Run EnricoMi/publish-unit-test-result-action@v1
Error: Container action is only supported on Linux
```

**Comment by EnricoMi** [comment]
Have you tried the composite version of this action?

    uses: EnricoMi/publish-unit-test-result-action/composite@v1

See the [README.md](https://github.com/EnricoMi/publish-unit-test-result-action#readme) for details.

**Comment by slavafomin** [comment]
Looks like I've missed it in a hurry, thank you for pointing this out. I would suggest to update the documentation to make it more clear.

**Comment by EnricoMi** [comment]
How is this emphasis: 386350d7?

**Comment by slavafomin** [comment]
I would suggest to use a headers for this, cause text could be simply missed, e.g.:

```markdown
## Usage: Ubuntu Linux

...

## Usage: MacOS / Windows

...
```

Also, the "composite" option, will it work for all platforms? If so, this could be better stated this way:

```markdown
## Usage: non-composite (Ubuntu Linux only)

...

## Usage: composite (Ubuntu Linux / MacOS / Windows)

...
```

**Comment by EnricoMi** [comment]
Yes, the composite version works for all OS but its startup is very slow. The container action is pre-built, immutable and very fast in starting up, so there is in general no reason to run the composite for Linux.

Listing the composite as Linux would add confusion as users might end up with the composite for Linux. Adding extra statements to avoid this would not increase clarity. At the top of the README, things should be as clear and simple as possible to get started. Thing become more complicated further down the README anyway.
