### ISSUE TITLE
Hours are printed wrongly if tests took >= 60 hours

### ISSUE THREAD

**Issue by qwrtyz** [EnricoMi/publish-unit-test-result-action#191]
In the as_stat_duration method in \_\_init__.py hours are cut by a % 60 operation which leads to incorrectly displayed time durations when tests took in total >= 60 hours. 

I discovered this because somehow in my junit test results xml (from android tests) time is outputted in milliseconds instead of seconds.

**Comment by EnricoMi** [comment]
This is one bug report and and feature request in one, great! Fixes are #192 and #193.

**Comment by EnricoMi** [comment]
@qwrtyz can you try this with your Android test results and see if times are reported correctly?

    uses: EnricoMi/publish-unit-test-result-action/composite@branch-configure-time-unit
    with:
      time_unit: milliseconds

**Comment by EnricoMi** [comment]
@qwrtyz both issues merged into master, to be released soon. Thanks for reporting!
