### ISSUE TITLE
Create GitHub issue when tests failed

### ISSUE THREAD

**Issue by mowies** [EnricoMi/publish-unit-test-result-action#197]
It would be great if this action could also post a new GitHub issue if tests failed.
This could be done by basically re-using the already existing things. The `check_name` could be the title of the issue and the content would be the report together with the logs and everything else.

My idea would be to have a separate configuration setting to switch between issue and PR publishing and the have a separate function in the [Publisher class](https://github.com/EnricoMi/publish-unit-test-result-action/blob/master/python/publish/publisher.py) to handle the new use case.

**Comment by EnricoMi** [comment]
Creating issues can become complex once you do not want to create duplicate issues, use your issue template, and so on. I think using an action that is specifically made for managing issues would be better, e.g. https://github.com/marketplace/actions/create-an-issue.

For that to work, this action should provide all its findings as output variables that can be used by a subsequent step to do whatever they want. I have created issue #199 for that.

**Comment by mowies** [comment]
That also makes a lot of sense! Then I will close this issue in favor of #199
