### ISSUE TITLE
Why this action cannot be executed on pull_request event ?

### ISSUE THREAD

**Issue by vincentBesseau** [EnricoMi/publish-unit-test-result-action#20]
I would like to execute this action only on pull request action why you by pass this event ? 

2020-09-23 17:48:11 +0000 - publish-unit-test-results - DEBUG - action triggered by 'pull_request' event
9
2020-09-23 17:48:11 +0000 - publish-unit-test-results - WARNING - event '{}' is not supported

**Comment by EnricoMi** [comment]
The action requires the commit sha of a specific commit. For a `pull`, this is the latest pushed commit and is provided via `GITHUB_SHA`. For `pull_request` the merge commit is provided via `GITHUB_SHA`. This is a merge of the latest pushed commit and the base commit. The commit sha that we need is available in the provided event payload.

Making this work for `pull_request` and `pull_request_target` is on the top of my list.

**Comment by EnricoMi** [comment]
Please try `uses EnricoMi/publish-unit-test-result-action@master`, this should now work for `pull_request`.

Please be aware that in situations where the pull request merges from a fork repository, the action will not be able to post a comment on your pull request with `pull_request`, because the action runs in the fork repo, the pull request is in your repo. Access will be denied.

To work for PRs from fork repos, you would need to use `pull_request_target`. Then, the action runs in our repo and can post to your PR.

**Comment by vincentBesseau** [comment]
Thank you for your responsiveness and for your explanations.
it work's for me :) !

**Comment by EnricoMi** [comment]
Thanks for letting me know, I will cut a new version soon, so you can point to a version rather than master.

**Comment by EnricoMi** [comment]
Here are more details on `pull_request` and `pull_request_target`: https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories

**Comment by EnricoMi** [comment]
I have just released v1.2. Cheers.

**Comment by mocsharp** [comment]
> Please try `uses EnricoMi/publish-unit-test-result-action@master`, this should now work for `pull_request`.
> 
> Please be aware that in situations where the pull request merges from a fork repository, the action will not be able to post a comment on your pull request with `pull_request`, because the action runs in the fork repo, the pull request is in your repo. Access will be denied.
> 
> To work for PRs from fork repos, you would need to use `pull_request_target`. Then, the action runs in our repo and can post to your PR.

Hi, new to GitHub Actions and just followed your readme using `pull_request_target` but I am not sure how to checkout the commit from the PR.  By default, `actions/checkout` checks out the master/main branch of the origin and not the PR from the forked branch.
 
Thanks!

**Comment by EnricoMi** [comment]
@mocsharp please open a new issue, even if you have only a question like that. I will try to help there. If your repository is public you can provide a link to the workflow yaml file and it will be easier for me to help.
