### ISSUE TITLE
Test results are not displayed, if the action is run by schedule

### ISSUE THREAD

**Issue by ant-siliconmint** [EnricoMi/publish-unit-test-result-action#203]
![image](https://user-images.githubusercontent.com/85300386/146548646-3df34aa2-9f20-45f4-ad91-f3801755a983.png)

Config:
```
- name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.25
        if: success() || failure()
        with:
          files: artifacts/**/*.xml
          check_name: Test_Results
```

Output:
```
2021-12-17 12:01:47 +0000 - publish-unit-test-results -  INFO - reading artifacts/**/*.xml
2021-12-17 12:01:47 +0000 - publish -  INFO - publishing failure results for commit 586a74bd947f5ac807e48e9544d1d24c4be7f2db
2021-12-17 12:01:47 +0000 - publish -  INFO - creating check
2021-12-17 12:01:49 +0000 - publish -  INFO - there is no pull request for commit 586a74bd947f5ac807e48e9544d1d24c4be7f2db
```

On push, the test results are displayed as expected:

![image](https://user-images.githubusercontent.com/85300386/146549305-31725e61-bf8b-41e3-9149-42eb05a2d9f2.png)

**Comment by EnricoMi** [comment]
The scheduled action will overwrite the push action's result and vice versa. The result of the scheduled action should be found in the same place as the push one.

The best way to find the result:

- click on the scheduled "Publish Test Results" action
- remove `?check_suite_focus=true` from the URL
- look in all workflow runs that are shown on the left, not necessarily the `scheduled` one

**Comment by ant-siliconmint** [comment]
I did find the results according to your instructions. And I guess there's no way to override this behavior and show the test results in a specific run?

**Comment by EnricoMi** [comment]
Yes, that location is picked by GitHub, their API does not allow to specify a workflow run (#12).

**Comment by ant-siliconmint** [comment]
Thank you, Enrico
