### ISSUE TITLE
Error processing result file: Invalid format.

### ISSUE THREAD

**Issue by ptsiogas** [EnricoMi/publish-unit-test-result-action#204]
I am getting an error `Error processing result file: Invalid format` when trying to give the [kotlinx-kover](https://github.com/Kotlin/kotlinx-kover) xml file as input.
If it is not supported, is it possible to do so?

**Comment by EnricoMi** [comment]
Looks like kotlinx-kover is about code coverage, not test results. Can you provide an example xml report or a specification of that file format?

**Comment by ptsiogas** [comment]
@EnricoMi you are right. So it's not an issue, my bad. I liked the comparison that you are doing and I would like to do something similar with the kover code coverage.

**Comment by EnricoMi** [comment]
I am not familiar with Kotlin, but I think you need to enable [JUnit XML reports for your test tasks](https://youtrack.jetbrains.com/issue/KT-32608#focus=Comments-27-3939854.0-0). Those results is what this action processes.

**Comment by ptsiogas** [comment]
@EnricoMi thanks, that did the trick just fine!

**Comment by EnricoMi** [comment]
Excellent!

**Comment by EnricoMi** [comment]
You could either specify the file pattern given via `files` in a way that it does not match the failsafe reposrts, or explicitly exclude the failsafe directory. The [configuration](https://github.com/EnricoMi/publish-unit-test-result-action#configuration) section in the README has details on how to do that:

> You can provide multiple file patterns, one pattern per line. Patterns starting with ! exclude the matching files. There have to be at least one pattern starting without a !:

**Comment by vivanovinrix** [comment]
Thanks a lot
