### ISSUE TITLE
Error on Windows Self-hosted runner

### ISSUE THREAD

**Issue by olivier-jourdan** [EnricoMi/publish-unit-test-result-action#211]
I get this error when I try to run the action on my self hosted runner (Windows Server 2019 Datacenter (1809))

![image](https://user-images.githubusercontent.com/88877400/149976063-62d44651-c498-4313-b007-bae6105e8d39.png)

It seems that a path is not formatted correctly, and I haven't any clue how to fix that.

Any idea?

**Comment by EnricoMi** [comment]
Is your repo public? Can you paste the workflow YAML here?

To me this looks like a general issue with your self-hosted runner as it does not seem to be able to execute _any_ bash shell code. The runner puts the shell code into a temporary file any tells `C:\Windows\system32\bash.EXE` to execute it, but it does not properly escape the ` \` in the path of the temporary file.

Does the following action work on your self-hosted runner:
```
   - run: ls
     shell: bash
```

**Comment by EnricoMi** [comment]
Looks like your error: https://github.com/actions/runner/issues/1328

**Comment by olivier-jourdan** [comment]
Thank you for your quick reply @EnricoMi 

The repo is not public, unfortunately.

Before getting this error, I had clear errors saying my runner couldn't execute bash shell code. I guessed I fixed that. Not completely, apparently… 
I'll test the action you said and keep you posted.

**Comment by olivier-jourdan** [comment]
Same error…

```
Run ls
  ls
  shell: C:\Windows\system32\bash.EXE --noprofile --norc -e -o pipefail {0}
/bin/bash: C:actions-runner_work_temp9928f894-24aa-42cc-b75c-7cc78ff93ccc.sh: No such file or directory
```

Bash is installed on my runner. I can execute it from powershell.

I'm missing something, but it's clearly not a bug on your side.
Thanks for your help. I'll try to figure out what's wrong and keep you posted for the record.

**Comment by EnricoMi** [comment]
Let me close this issue then but please report back when you know what the problem and fix is.

**Comment by EnricoMi** [comment]
I have recently used a self-hosted Windows runner myself. I have installed Git BASH, added the location of `bash.exe` to PATH and used that shell with my action. This handled the backslashes in the path just fine.

What bash did you use? How did you install `C:\Windows\system32\bash.EXE`?

**Comment by EnricoMi** [comment]
@olivier-jourdan do you remember how you installed `C:\Windows\system32\bash.EXE` on your self-hosted WIndows runner?
