### ISSUE TITLE
Error: Container action is only supported on Linux

### ISSUE THREAD

**Issue by TWiStErRob** [EnricoMi/publish-unit-test-result-action#239]
Workflow: https://github.com/TWiStErRob/net.twisterrob.colorfilters/blob/509923857a5c26eb524fd84f8ca02c3b9bfb6fd5/.github/workflows/CI.yml (it's on https://github.com/TWiStErRob/net.twisterrob.colorfilters/pull/37)

Failed execution: https://github.com/TWiStErRob/net.twisterrob.colorfilters/runs/5636051024?check_suite_focus=true#step:9:27

![image](https://user-images.githubusercontent.com/2906988/159445385-74c72bac-4d92-4f68-9764-de92623594c7.png)

Another failed execution with all debug on:
https://github.com/TWiStErRob/net.twisterrob.colorfilters/runs/5641228182?check_suite_focus=true#step:9:61

**Comment by EnricoMi** [comment]
Yes, what is the question here? As the error says: Github only supports "Container" actions on Linux. See the [README.md](https://github.com/EnricoMi/publish-unit-test-result-action/blob/master/README.md) for instructions on how to run this on Windows and macOS:

    Use this for macOS (e.g. runs-on: macos-latest) and Windows (e.g. runs-on: windows-latest) runners:

**Comment by TWiStErRob** [comment]
🤦🏻‍♂️ sorry, man. That's a big miss. I looked at the 3 tags on top and somehow didn't notice the 1 word difference.

I'm guessing you don't control this error message, but if you do, can you add: "Please use EnricoMi/publish-unit-test-result-action/composite instead.`

**Comment by EnricoMi** [comment]
Nope, that message is coming from GitHub Actions runner. That error message would be useful. Message that say what to do rather than what is wrong are usually a great idea. But the runner cannot know, in this case.
