### ISSUE TITLE
More debug info?

### ISSUE THREAD

**Issue by TWiStErRob** [EnricoMi/publish-unit-test-result-action#240]
In the issue template you have this:
````
If the error occurs repeatedly, please consider adding this to the publish action, to collect more information on the issue:

```yaml
with:
  root_log_level: DEBUG
  log_level: DEBUG
```
````

Would adding this link give you additional context:
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging

You can find an example here: https://github.com/EnricoMi/publish-unit-test-result-action/issues/239

Also notice the warning for the DEBUG keys, is that normal?

**Comment by EnricoMi** [comment]
That is interesting, thanks for sharing. This provides debug information from the GitHub Actions runner itself.

You probably refer to this warning:

    Unit Test Results (reference)
    Unexpected input(s) 'log_level', valid inputs are ...

This is because the log level arguments are not documented. So that is fine.
