### ISSUE TITLE
Support publishing to all open pull requests

### ISSUE THREAD

**Issue by lachaib** [EnricoMi/publish-unit-test-result-action#242]
In my company, it is very usual to open several pull requests at once from the same branch (targeting different environments).
A common similar case would be when you make a hotfix and create pull requests both to `prod` and `main` branches at once.
Therefore, we fall most of the time into the error 
`Error: Found multiple open pull requests in repo [...] with commit [...] as current head or merge commit`

I would like this action to support commenting all open pull requests matching the query done.

Reading over the code, I think we could rework the `if` [condition](https://github.com/EnricoMi/publish-unit-test-result-action/blob/master/python/publish/publisher.py#L101) to a for loop, and rework the [get_pull](https://github.com/EnricoMi/publish-unit-test-result-action/blob/master/python/publish/publisher.py#L114) method to return a list of open pull requests.

Would you agree with that?
I'm open to making the changes if you flag it as "Good First Issue" 😄

**Comment by EnricoMi** [comment]
I fully agree. Just wondering if this should be the default behaviour or a special feature. Might there be a common situation where multiple PRs exist where you don't want test results to be published to all of them?

**Comment by lachaib** [comment]
I honestly don't have any idea when I'd want an open PR not to be aware of latest build status on their head commit. Maybe forks/dependabot PRs? Still, if the action is able to decorate them, I don't see why not.
As you're owner, I let you decide whether we go for a setting or a default behavior.

**Comment by EnricoMi** [comment]
Finding PRs for a commit also returns PRs in forks. I think I was thinking of that situation, but since PRs only from the "current" repo are considered now, this is not an issue any more. So I cannot think of a situation where it is not desirable to decorate all PRs in the repo with test results for a given commit.

When someone comes up with a use case of not decorating all PRs, we can come up with a way to configure this.

So please go ahead!

**Comment by EnricoMi** [comment]
Github UI does not seem to support multiple PRs in the same repo for one source branch very well. Once a branch has a pull request, the UI does not provide you with a button to create a new PR (in the various places where this is possible), but links to the existing PR.

The only way to create additional PRs through the UI that I have found is to compare your source branch with your second target branch by constructing the right URL following this pattern: https://github.com/{USER}/{REPO}/compare/{TARGET}...{SOURCE}. That branch-compare page allows you to create a PR for your other target branch.

Once you have multiple PRs in your repo for your branch, the UI fails to show them all. The [branches](https://github.com/EnricoMi/publish-unit-test-result-action/branches) page only shows one PR per branch, probably the one created first, while the individual [branch](https://github.com/EnricoMi/publish-unit-test-result-action/tree/branch-viz-ai-better-formatting) pages only shows the PR created last.

How do you keep track of all the PRs for a given branch in the GitHub UI?

**Comment by lachaib** [comment]
We create them with command-line 😆
