### ISSUE TITLE
Error: Docker pull failed with exit code 1

### ISSUE THREAD

**Issue by anas-baadshah** [EnricoMi/publish-unit-test-result-action#257]
> Pull down action image 'ghcr.io/enricomi/publish-unit-test-result-action:v1.33'
>   /usr/bin/docker pull ghcr.io/enricomi/publish-unit-test-result-action:v1.33
>   Error response from daemon: Head "https://ghcr.io/v2/enricomi/publish-unit-test-result-action/manifests/v1.33": Get "https://ghcr.io/token?scope=repository%3Aenricomi%2Fpublish-unit-test-result-action%3Apull&service=ghcr.io": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
>   Warning: Docker pull failed with exit code 1, back off 6.11[8](6155661254?check_suite_focus=true#step:2:8) seconds before retry.
>   /usr/bin/docker pull ghcr.io/enricomi/publish-unit-test-result-action:v1.33
>   Error response from daemon: Head "https://ghcr.io/v2/enricomi/publish-unit-test-result-action/manifests/v1.33": Get "https://ghcr.io/token?scope=repository%3Aenricomi%2Fpublish-unit-test-result-action%3Apull&service=ghcr.io": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
>   Warning: Docker pull failed with exit code 1, back off 7.726 seconds before retry.
>   /usr/bin/docker pull ghcr.io/enricomi/publish-unit-test-result-action:v1.33
>   Error response from daemon: Head "https://ghcr.io/v2/enricomi/publish-unit-test-result-action/manifests/v1.33": Get "https://ghcr.io/token?scope=repository%3Aenricomi%2Fpublish-unit-test-result-action%3Apull&service=ghcr.io": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
> Error: Docker pull failed with exit code 1

**Comment by EnricoMi** [comment]
That docker registry is provided by GitHub, see [Github Status](https://www.githubstatus.com) for incidents.

There was an incident that they have resolved: https://www.githubstatus.com/incidents/b40k7ckrs7sp.
