### ISSUE TITLE
Publish results as job summary

### ISSUE THREAD

**Issue by lachaib** [EnricoMi/publish-unit-test-result-action#264]
Hello,

Today, GitHub have [announced](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) the possibility to display markdown in job summary (by the way, their example is the display of test results).
I think it's truly awesome, and I would appreciate if this action could offer the mode "summary" to report the unit test results instead of decorating pull request. Or maybe in complement?
Anyways, I'd be glad to contribute if you agree with this suggestion.

**Comment by EnricoMi** [comment]
Thanks for sharing. I agree, it would be great if the action would also publish the markdown as this new summary. Please go for it.

**Comment by EnricoMi** [comment]
This has been released, enjoy!
