### ISSUE TITLE
Make cross for failed tests red

### ISSUE THREAD

**Issue by erik-f** [EnricoMi/publish-unit-test-result-action#27]
For me (Windows 10, Firefox and Chrome) the cross ✖️ for failed tests is grey and not red like in the screenshots.
I feel like failed tests get lost this way and should rather be bright red. You could use this unicode character instead: ❌

**Comment by EnricoMi** [comment]
Can you send me a screenshot for these test results please:
- https://github.com/horovod/horovod/pull/2371#issuecomment-708571788
- https://github.com/horovod/horovod/runs/1255050458

Annoying that github can't control its appearance across OS.

**Comment by erik-f** [comment]
![grafik](https://user-images.githubusercontent.com/44124897/96269830-29dc1900-0fcb-11eb-95c1-0897f08fed5d.png)
![grafik](https://user-images.githubusercontent.com/44124897/96269845-2e083680-0fcb-11eb-9ddf-32e1566c69c9.png)

**Comment by erik-f** [comment]
I created a PR in case you agree with my changes. It is red for me now.
