### ISSUE TITLE
How to resolve github-action error when docker pull?

### ISSUE THREAD

**Issue by meloning** [EnricoMi/publish-unit-test-result-action#273]
![스크린샷 2022-05-16 오후 2 47 31](https://user-images.githubusercontent.com/50299857/168527419-f6526216-6c20-46f3-9917-447ae5c94cfa.png)

I am experiencing the same problem as above, but I have not been able to solve it even though I have done github-action re-run jobs.

How to solve the above problem?

Please answer fast.
Thank you

**Comment by EnricoMi** [comment]
Does the error persist?

**Comment by meloning** [comment]
It's fine now. :) Can you tell me what is the cause?

**Comment by EnricoMi** [comment]
The image is hosted by `ghcr.io`, this is GitHub container registry. That is infrastructure supported by GitHub, so out of my control. See #257.
