### ISSUE TITLE
Job Summary

### ISSUE THREAD

**Issue by ben-manes** [EnricoMi/publish-unit-test-result-action#274]
This [new feature](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) might avoid the quirkiness of where the test results are attached. You just export the markdown to [$GITHUB_STEP_SUMMARY](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables).

Looks like a PM at Github made a project that does this, 
https://github.com/test-summary/action

![image](https://user-images.githubusercontent.com/378614/168710905-eb7b1520-061a-4fe8-aa84-7891f161f7e4.png)

**Comment by EnricoMi** [comment]
This has been added in #266 and released as [v1.35](https://github.com/EnricoMi/publish-unit-test-result-action/releases/tag/v1.35). See #264.

Please move to the latest version or use v1, which always refers to the latest v1.xx release. Please confirm that this is working for you.

Thanks for reporting, though!

**Comment by ben-manes** [comment]
Oh neat! Sorry that I missed this change. I’ll give it a spin. 🙂

**Comment by ben-manes** [comment]
Yep, I completely missed it!

https://github.com/ben-manes/caffeine/actions/runs/2336457770
