### ISSUE TITLE
Question: dynamic check suite and run title

### ISSUE THREAD

**Issue by TWiStErRob** [EnricoMi/publish-unit-test-result-action#281]
Hey, @EnricoMi I noticed that your check suite has a custom title, that's very useful to understand at a glance what happened (3rd line):

![image](https://user-images.githubusercontent.com/2906988/169669373-61574459-251e-4e50-9a14-11ac47052b13.png)

I'm wondering if you know if there's a way to change the same for simple runs (e.g. 1st line on screenshot), from "Failing after" to something that I provide in yaml dynamically?

For reference the CI.yml: https://github.com/TWiStErRob/net.twisterrob.sun/blob/master/.github/workflows/CI.yml

**Comment by EnricoMi** [comment]
That is a job in a GitHub actions workflow. Than summary cannot be modified as GitHub Actions picks that text. No configuration possible.

**Comment by TWiStErRob** [comment]
Thank you! That makes sense. After further investigation I found this:
https://github.com/TWiStErRob/github-actions-test/blob/main/.github/workflows/custom-status.yml

At first I was looking into creating a custom check suite like you do, but then this was more suited to what I was looking for.
