### ISSUE TITLE
Add minimal localization support

### ISSUE THREAD

**Issue by ben-manes** [EnricoMi/publish-unit-test-result-action#282]
It might be nice to localize the thousands separator, e.g. using [locale.LC_NUMERIC](https://docs.python.org/3/library/locale.html#locale.LC_NUMERIC). For the badge, I switched to commas via `LANG=en_US.utf8` and `printf`.

https://github.com/EnricoMi/publish-unit-test-result-action/blob/9f4c8458e643883ec77453cbfa67ef4e0d4a50ef/python/publish/__init__.py#L18

**Comment by EnricoMi** [comment]
This has been fixed in #298. Use `json_thousands_separator` to pick your favorite thousands separator character.

**Comment by ben-manes** [comment]
I noticed that the badge uses the custom separator, but that the job summary does not. Not a problem for me, but probably an oversight.

https://github.com/ben-manes/caffeine/actions/runs/2431285812

**Comment by ben-manes** [comment]
I see. That is why I suggested adopting `LANG` whose default could be your space. Then changing it could reformat all usages, which I think could be delegated to the `locale` package. I had hoped it would side step that concern.
