### ISSUE TITLE
Improve logging reading the files

### ISSUE THREAD

**Issue by Speiger** [EnricoMi/publish-unit-test-result-action#304]
o/ I have been successfully using this action for a smaller scale.
But ever since I started the full on Test Suite, it just started failing. (11 Million Unit tests were added)
Sadly there isn't a log of why that is happening.
Anything that I can do to fix that?
My guess at this point is that I am running out of ram, but I am not sure how to add more ram to a github actions task.
Anything I can do?

Here is my data:
https://github.com/Speiger/Primitive-Collections/runs/6858679563

**Comment by EnricoMi** [comment]
Yes, `ignore_runs: true` is what you need. The VM / action simply runs out of memory and cannot report anything.

**Comment by Speiger** [comment]
@EnricoMi Would be nice to provide a bit of logging why it fails. Maybe also a option to increase the ram since github actions has up to 7GB of ram.

**Comment by EnricoMi** [comment]
I believe Python uses all the available memory, so there is no way in increasing anything. I could add some logging that indicates the file size and available memory, which might help to identify the issue quicker.

But GitHub Actions makes it hard to log something when the underlying execution platform dies.

**Comment by EnricoMi** [comment]
True, fixed in #305, to be released.

**Comment by Speiger** [comment]
@EnricoMi Ping me once released. I assume since I am one of the larger ones using your tools I am willing to try to see how well it works.

**Comment by EnricoMi** [comment]
This has just been released. Enjoy!

**Comment by Speiger** [comment]
Startet test runs.
https://github.com/Speiger/Primitive-Collections/actions/runs/2534638487
I activated testruns too to see if it works now better.

**Comment by Speiger** [comment]
So we had a fail. One thing i noticed the JVM wasn't killed when your task was running because only 3GB ram was free.
So i need to figure out how to kill the JVM and keep the cache to then run your task with the full 7GB.
