### ISSUE TITLE
In Android, the pipeline doesn't work

### ISSUE THREAD

**Issue by yoonhok524** [EnricoMi/publish-unit-test-result-action#306]
I am developing an Android app.
It contains multiple modules.

So when I run the test, test results are generated on multiple folders.
```
./gradlew test
```
like:
```
rootprj/app/build/test-results/...
rootprj/domain/build/test-results/...
rootprj/data/build/test-results/...
```

So the pipeline is failed with `Could not find any files for test-results/**/*.xml`

**Comment by EnricoMi** [comment]
Did you try wildcards for the modules part of the paths?

```
  with:
    files: "rootprj/**/build/test-results/**/*.xml"
```

**Comment by EnricoMi** [comment]
Please reopen if you are still seeing problems.
