### ISSUE TITLE
Unauthenticated error when trying to pull image locally or during GitHub Action.

### ISSUE THREAD

**Issue by hplar** [EnricoMi/publish-unit-test-result-action#307]
I'm having the following error from Docker while trying to pull the action image into our GitHub Action, but also on my local machine:

```
❯ docker pull ghcr.io/enricomi/publish-unit-test-result-action:v1.38
v1.38: Pulling from enricomi/publish-unit-test-result-action
2408cc74d12b: Pulling fs layer
2f22aa6a21a6: Pulling fs layer
b7017d904e36: Pulling fs layer
0b104bf00a69: Waiting
00abd2ad2194: Waiting
eb7149e59b10: Waiting
3899c6e458cc: Waiting
c708ef03a3db: Waiting
b58c806264a5: Waiting
9c3f1c2099b9: Waiting
error pulling image configuration: unauthorized: unauthenticated: User cannot be authenticated with the token provided.
```

**Comment by NaLDo627** [comment]
same here

**Comment by ascopes** [comment]
Can also reproduce.

<details>
  <summary>Output</summary>
  <pre>
  Warning: Docker pull failed with exit code 1, back off 7.217 seconds before retry.
  /usr/bin/docker pull ghcr.io/enricomi/publish-unit-test-result-action:v1.38
  v1.38: Pulling from enricomi/publish-unit-test-result-action
  2408cc74d12b: Already exists
  2f22aa6a21a6: Pulling fs layer
  b7017d904e36: Pulling fs layer
  0b104bf00a69: Pulling fs layer
  00abd2ad2194: Pulling fs layer
  eb7149e59b10: Pulling fs layer
  3899c6e[45](https://github.com/assertj/assertj-core/runs/7003703698?check_suite_focus=true#step:2:45)8cc: Pulling fs layer
  c708ef03a3db: Pulling fs layer
  b58c806264a5: Pulling fs layer
  9c3f1c2099b9: Pulling fs layer
  00abd2ad2194: Waiting
  c708ef03a3db: Waiting
  b58c806264a5: Waiting
  9c3f1c2099b9: Waiting
  eb71[49](https://github.com/assertj/assertj-core/runs/7003703698?check_suite_focus=true#step:2:49)e59b10: Waiting
  3899c6e4[58](https://github.com/assertj/assertj-core/runs/7003703698?check_suite_focus=true#step:2:58)cc: Waiting
  error pulling image configuration: download failed after attempts=1: unauthorized: unauthenticated: User cannot be authenticated with the token provided.
Error: Docker pull failed with exit code 1
  </pre>
</details>

**Comment by dbramwell** [comment]
pinning to @1.37 doesn't seem to fix it

**Comment by peterfortuin** [comment]
I also tied to pin in to v1.37 and that doesn't resolve the issue. The problem didn't start with the release of v1.38. That came out yesterday and the problem started today (somewhere in the last hour).

**Comment by MGough** [comment]
It appears Github are now aware: https://www.githubstatus.com/incidents/10vm6ctn52gx

**Comment by EnricoMi** [comment]
Another incident with GitHub Packages, resolved three minutes ago: https://www.githubstatus.com/incidents/10vm6ctn52gx
