### ISSUE TITLE
docker pull error

### ISSUE THREAD

**Issue by meloning** [EnricoMi/publish-unit-test-result-action#308]
```
docker: error pulling image configuration: download failed after attempts=1: unauthorized: unauthenticated: User cannot be authenticated with the token provided.
```

The above is happening.

Please act quickly.

![스크린샷 2022-06-22 오후 9 24 47](https://user-images.githubusercontent.com/50299857/175028271-87a1c5d8-e5f2-45fd-a524-336a5916aba0.png)

**Comment by gresnick** [comment]
+1

Blocking issue

**Comment by peterfortuin** [comment]
Same thing happend in my repository.

**Comment by mmahrous** [comment]
+1

**Comment by MGough** [comment]
Duplicate of #307 - Github are aware of the issue as it's happening for multiple GHCR images: https://www.githubstatus.com/incidents/10vm6ctn52gx
