### ISSUE TITLE
How to test for .js files

### ISSUE THREAD

**Issue by mydearmuthu1978** [EnricoMi/publish-unit-test-result-action#309]
I am using serverless applications where i use node js script. I am trying to run npm test to generate the unit test report.
could you please provide me the option to use .js files to publish the report as part of github actions?
currently the feature you provides works only for .xml files. It would be great if you could provide option to use it for .js files.

**Comment by EnricoMi** [comment]
Is there a format specification for those `.js` files? Is there a way to generate JUnit xml files instead?

**Comment by mydearmuthu1978** [comment]
I believe the current format support for .xml files inside test folder. I am working on serverless deployments for which i have all my test scripts are .js inside my test folder. If i use this component, i am getting error saying that "format is not supported". please find the below error for your reference.

[Error processing result file: tests/local-test.js#L1](https://github.com/xxx-xdddd)
File is not a valid XML file: syntax error: line 1, column 0

**Comment by EnricoMi** [comment]
This sounds like you are pointing this action to the `.js` test scripts. This action expects result files, not test files. So you execute the test files and produce result files. Common format for those result files are JUnit XML files.

The link that you provided does not work. Is the repo private?
