### ISSUE TITLE
Error : GithubException: 403 {"message": "You must authenticate via a GitHub App

### ISSUE THREAD

**Issue by sri59677** [EnricoMi/publish-unit-test-result-action#31]
github.GithubException.GithubException: 403 {"message": "You must authenticate via a GitHub App.", "documentation_url": "https://docs.github.com/rest/reference/checks#create-a-check-run"}

**Comment by EnricoMi** [comment]
@sri59677 what was the situation where this error occurred and how did you fix it? Or was it transient?

**Comment by sri59677** [comment]
I entered GITHUB TOKEN in secrets thats why i got issue

**Comment by EnricoMi** [comment]
So this was a typo on your side. Thanks for clarification.

**Comment by gokulnath-03** [comment]
Hi @sri59677 @EnricoMi I am Using this curl command to send results 
curl -L \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: token $(gitToken)" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/$owner/$repo/check-runs \
  -d '{
    "name": "Test Results",
    "head_sha": "$(Build.SourceVersion)",
    "status": "completed",
    "conclusion": "success",
    "output": {
      "title": "Test Results",
      "summary": "Summary of test results",
      "text": "'"$(cat $(Build.SourcesDirectory)/TestResults/unitResults.html)"'"
    }
  }'
  
but Still, I am getting {"message": "You must authenticate via a GitHub App.", "documentation_url": "[https://docs.github.com/rest/reference/checks#create-a-check-run"}](https://docs.github.com/rest/reference/checks#create-a-check-run%22%7D)

**Comment by gokulnath-03** [comment]
Hi @sri59677 @EnricoMi I am Using this curl command to send results
curl -L
-X POST
-H "Accept: application/vnd.github+json"
-H "Authorization: token $(gitToken)"
-H "X-GitHub-Api-Version: 2022-11-28"
https://api.github.com/repos/$owner/$repo/check-runs \
-d '{
"name": "Test Results",
"head_sha": "$(Build.SourceVersion)",
"status": "completed",
"conclusion": "success",
"output": {
"title": "Test Results",
"summary": "Summary of test results",
"text": "'"$(cat $(Build.SourcesDirectory)/TestResults/unitResults.html)"'"
}
}'

but Still, I am getting {"message": "You must authenticate via a GitHub App.", "documentation_url": "https://docs.github.com/rest/reference/checks#create-a-check-run"}
