### ISSUE TITLE
Include check URL in JSON output

### ISSUE THREAD

**Issue by danxmoran** [EnricoMi/publish-unit-test-result-action#310]
Downstream steps process the JSON output of this action. We'd like them to be able to link back to the created check, but (as far as I can tell) there's no way for them to get that information. It'd be convenient if the link to the check was included in the action's JSON output.

**Comment by EnricoMi** [comment]
Excellent idea!

**Comment by danxmoran** [comment]
I'm happy to contribute 😄 working on it now, should have a PR up shortly

**Comment by danxmoran** [comment]
@EnricoMi any chance you could cut a `v1.39` release with this change today? 😄

**Comment by EnricoMi** [comment]
Done, enjoy!
