### ISSUE TITLE
Job summary commit link is not clickable

### ISSUE THREAD

**Issue by TWiStErRob** [EnricoMi/publish-unit-test-result-action#312]
![image](https://user-images.githubusercontent.com/2906988/175696047-21ae97d2-eb49-4060-beb5-de918fe0bba5.png)
```
## 🔔 Test Results
  55 files    55 suites   9m 16s [:stopwatch:](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v1.20/README.md#the-symbols "duration of all tests")
207 tests 204 [:heavy_check_mark:](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v1.20/README.md#the-symbols "passed tests") 3 [:zzz:](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v1.20/README.md#the-symbols "skipped / disabled tests") 0 [:x:](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v1.20/README.md#the-symbols "failed tests")
210 runs  207 [:heavy_check_mark:](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v1.20/README.md#the-symbols "passed tests") 3 [:zzz:](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v1.20/README.md#the-symbols "skipped / disabled tests") 0 [:x:](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v1.20/README.md#the-symbols "failed tests")

Results for commit f1904eb6.
```

Live: https://github.com/TWiStErRob/net.twisterrob.cinema/actions/runs/2558212173

Looks like GH smarts are not enabled there.

**Comment by EnricoMi** [comment]
Yes, this is sad. Github does not render this MD as it does anywhere else. I guess they will recognize and fix this soon. Nothing I can workaround on my side.

**Comment by TWiStErRob** [comment]
Isn't [{sha.substring(0,7)}]({repo}/commits/{sha}) aan option? That's also future proof if they fix it ☺️.

**Comment by EnricoMi** [comment]
Yes, that would make the sha's clickable, but I don't like the idea to add complexity to workaround a bug on their side that I think should be easy to fix. I would have to generate different MD for the job summary than for the comments and check runs. That is code smell.
