### ISSUE TITLE
Add annotations to changed files

### ISSUE THREAD

**Issue by AntonOellerer** [EnricoMi/publish-unit-test-result-action#32]
Hey, I really like your library!
Is there a plan currently to implement adding annotations so that they can be seen in the "files changed" tab?
Best regards
Anton

**Comment by EnricoMi** [comment]
This is a bit tricky to achieve given the way github works. The files changed tab only shows those parts of files that have changed. The unit test result files used by the action to report test results only report which unit tests in which unit test files and lines failed. Both things usually don't occur at the same time, unless you have touched a unit test (changed files) that fails (unit test result). Usually you change code and unit tests fail.

I think the current annotations provided by the action already implements that rare case.

I think what you refer to (and I agree that would be useful) is a snippet of the unit test that failed, regardless of it's change state (changed files). Maybe a link to the source line would work (given the action knows the commit, file and line).

**Comment by AntonOellerer** [comment]
Ah I see, thank you!

**Comment by EnricoMi** [comment]
Happy to help!
