### ISSUE TITLE
Parsing error in v2

### ISSUE THREAD

**Issue by ben-manes** [EnricoMi/publish-unit-test-result-action#321]
> Check failure on line 0 in caffeine-weakKeysAndWeakValuesStatsSyncGuavaTest-18/caffeine/build/reports/weakKeysAndWeakValuesStatsSyncGuavaTest/results/TEST-com.github.benmanes.caffeine.cache.ExpirationTest.xml
>
> Error processing result file
__init__() takes at least 5 positional arguments (2 given)

https://github.com/ben-manes/caffeine/runs/7192336253

```
$ head -2 caffeine/build/reports/weakKeysAndWeakValuesStatsSyncGuavaTest/results/TEST-com.github.benmanes.caffeine.cache.ExpirationTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.github.benmanes.caffeine.cache.ExpirationTest" tests="4626" skipped="0" failures="0" errors="0" timestamp="2022-07-04T19:35:40" hostname="fv-az135-432" time="7.814">
```

[caffeine-weakKeysAndWeakValuesStatsSyncGuavaTest-18-results.zip](https://github.com/EnricoMi/publish-unit-test-result-action/files/9044620/caffeine-weakKeysAndWeakValuesStatsSyncGuavaTest-18-results.zip)

**Comment by EnricoMi** [comment]
Thanks for reporting this, I am looking into it.

**Comment by EnricoMi** [comment]
Strange, I cannot reproduce this error, but a different one: https://github.com/EnricoMi/python/runs/7199188775?check_suite_focus=true

**Comment by EnricoMi** [comment]
I did not run the action with `ignore_runs: true`, that may have eclipsed your error.

**Comment by EnricoMi** [comment]
I still cannot reproduce this: https://github.com/EnricoMi/python/runs/7199682774?check_suite_focus=true

It downloads all 56 artifacts from your workflow run, extracts it the same way and then publishes the files. It only reports 559 files, not 1047, which is really strange. And it does not see any errors.

**Comment by ben-manes** [comment]
hmm.. yes. I'm not sure either. I'll try to dig in this evening PT. I have the commit on the v3.dev branch for reproducing.

**Comment by EnricoMi** [comment]
I can reproduce the issue, looks like a problem with lxml. I'll raise a bug report with them.

**Comment by ben-manes** [comment]
sure!
https://github.com/ben-manes/caffeine/actions/runs/2614871044

**Comment by ben-manes** [comment]
worked perfectly!
