### ISSUE TITLE
Is v2 released?

### ISSUE THREAD

**Issue by TWiStErRob** [EnricoMi/publish-unit-test-result-action#326]
If yes, what changed? https://github.com/EnricoMi/publish-unit-test-result-action/releases has no stable v2 yet.

ref https://github.com/TWiStErRob/net.twisterrob.cinema/pull/162

**Comment by EnricoMi** [comment]
still not stable, here are most notable changes:
https://github.com/EnricoMi/publish-unit-test-result-action/releases/tag/v2.0.0-alpha

**Comment by EnricoMi** [comment]
This has just been released.
