### ISSUE TITLE
Self Hosted Runner Bash Access Denied

### ISSUE THREAD

**Issue by jalvini** [EnricoMi/publish-unit-test-result-action#334]
Hello, 

I left a comment on another issue that was closed that was similar to this one but thought it would be a little more appropriate to start a new issue for this problem. 

I am running into this problem, I installed Git Bash and I added the path which is C:\Program Files\Git\bin to the environment variables paths. Everything almost worked but now I am getting the following error:

```
Run EnricoMi/publish-unit-test-result-action/composite@v1
o '##[group]Check for Python3'
echo '##[group]Check for Python3'
  o '##[endgroup]'
shell: C:\Windows\system32\bash.EXE --noprofile --norc -e -o pipefail {0}
```

Access is denied.

Error: Process completed with exit code -1.

Any idea why this may be happening?

**Comment by jalvini23** [comment]
BTW here is the entire log:

```
Run EnricoMi/publish-unit-test-result-action/composite@v1
  with:
    files: tests/**/*.xml
    github_token: ***
    github_retries: 10
    check_name: Unit Test Results
    comment_mode: always
    fail_on: test failures
    time_unit: seconds
    ignore_runs: false
    hide_comments: all but latest
    job_summary: true
    compare_to_earlier_commit: true
    pull_request_build: merge
    check_run_annotations: all tests, skipped tests
    seconds_between_github_reads: 0.[2](https://github.com/{Company_Dir}/{Proj_Dir}/runs/654345678?check_suite_focus=true#step:3:2)5
    seconds_between_github_writes: 2.0
    json_thousands_separator:  
o '##[group]Check for Python[3](https://github.com/{Company_Dir}/{Proj_Dir}/runs/654345678?check_suite_focus=true#step:3:3)'
echo '##[group]Check for Python3'
  # we check version here just to execute `python3` with an argument
  # on Windows, there is a `python3.exe` that is a proxy to trigger installation from app store
  # command `which python3` finds that, but `python3 -V` does not return the version on stdout
  if ! which python3 || [[ $(python3 -V) != *"python 3."* && $(python3 -V) != *"Python 3."* ]]
  then
    if ! which python || [[ $(python -V) != *"python 3."* && $(python -V) != *"Python 3."* ]]
    then
      echo "::error::No python3 interpreter found. Please setup python before running this action. You could use https://github.com/actions/setup-python."
      exit 1
    fi
  
    interpreter="$(which python)"
    if [[ ! -e "${interpreter}3" ]]
    then
      mkdir -p "$RUNNER_TEMP/bin/"
      ln -s "$interpreter" "$RUNNER_TEMP/bin/python3"
      echo "$RUNNER_TEMP/bin" >> $GITHUB_PATH
    fi
  fi
  o '##[endgroup]'
shell: C:\Windows\system[32](https://github.com/{Company_Dir}/{Proj_Dir}/runs/654345678?check_suite_focus=true#step:3:33)\bash.EXE --noprofile --norc -e -o pipefail {0}

Access is denied.



Error: Process completed with exit code -1.
```

**Comment by jalvini23** [comment]
Following up, shouldn't the path:

C:\Windows\system32\bash.EXE

Be pointing to:

C:\Program Files\Git\bin

My Environment variable for Path is pointing to C:\Program Files\Git\bin.

**Comment by EnricoMi** [comment]
This is problem is not specific to this action but a general issue with self-hosted Windows runner. Please check with GitHub to get help on how to setup your self-hosted Windows runner.

Did you configure `Path` or `PATH`? Did you use `;` or `:` as delimiter? Did you add `C:\Program Files\Git\bin` at the front of the variable or at the end? Did you modify the system-wide environment variable or the user-specific variable? Did you restart the runner process? Did you restart the terminal that runs the runner?

There are so many possible reasons why the runner does not pick up the modified `PATH` environment variable.

**Comment by jalvini23** [comment]
My very first System environment variable for Path is C:\Program Files\Git\bin
I also did restart the Runner. As far as the terminal, how would I do that? Would that be done by going into task manager and killing the process?

**Comment by EnricoMi** [comment]
Simply type `exit` or press CTRL+D and open a new terminal.

**Comment by EnricoMi** [comment]
Please reopen if needed.
