### ISSUE TITLE
How to specify multiple file path patterns

### ISSUE THREAD

**Issue by kwerle** [EnricoMi/publish-unit-test-result-action#335]
This is not so much a bug as a request for documentation improvement.

I want to publish the results from "path/**/*.xml" and "path/**/*.junit".  I can do either one, but I have not figured out the magic incantation that will get me the results for both.

What
```
          files: "..."
```
do I need to use?

**Comment by EnricoMi** [comment]
Are the double `/` in your path deliberately?

Try:
```yaml
with:
  files: |
    path/*.xml
    path/*.junit
```

Section [Configuration](https://github.com/EnricoMi/publish-unit-test-result-action#configuration) mention this multi-pattern syntax.

**Comment by kwerle** [comment]
How did I miss that!?  Thank you so much!
