### ISSUE TITLE
Support of PAT as input for `github_token`

### ISSUE THREAD

**Issue by roventu** [EnricoMi/publish-unit-test-result-action#340]
Hi!
First of all, thanks for this amazing action! I am now trying out the `v2` and wanted to ask if there are any plans to support a `PAT` as input of the parameter `github_token` ? 
If I understood it correctly, you tried this out on https://github.com/EnricoMi/publish-unit-test-result-action/pull/80 but I'm not sure if that test made it to productive code.
Is there a reason why we can't pass a PAT?

Thanks and best regards!
Rodrigo

**Comment by EnricoMi** [comment]
Hi Rodrigo, thank for sponsoring this work.

I cannot remember the outcome of that test. The action has changed a lot since then, I will try it with a PAT and update README.md with information on how to use the action with PAT.

**Comment by EnricoMi** [comment]
This action publishes test results in four ways: https://github.com/EnricoMi/publish-unit-test-result-action#publishing-test-results
1. as [a comment](https://github.com/EnricoMi/publish-unit-test-result-action#pull-request-comment) in related pull requests
2. as [a check](https://github.com/EnricoMi/publish-unit-test-result-action#commit-and-pull-request-checks) in the checks section of a commit and related pull requests
3. as [a job summary](https://github.com/EnricoMi/publish-unit-test-result-action#github-actions-job-summary) of the GitHub Actions workflow
4. as [a check summary](https://github.com/EnricoMi/publish-unit-test-result-action#github-actions-check-summary-of-a-commit) in the GitHub Actions section of the commit

Step 2. and 4. require write access to the Checks API, which cannot be granted through a PAT:
```
Write permission for the Checks API is only available to GitHub Apps. OAuth Apps and authenticated users
can view check runs and check suites, but they are not able to create them.
```

What I can do:
- add option to disable creating checks
- use the [Commit Status API](https://docs.github.com/en/rest/commits/statuses#create-a-commit-status) in that case to create 2.

Then, only 4. is missing, which provides the annotations container test failure details.

**Comment by EnricoMi** [comment]
Can you provide me some more background on why you want to use a PAT rather than the Github Actions token?

**Comment by roventu** [comment]
Hi Enrico, firs off: thanks a lot for your reply! I understand now better the reason why I was not able to pass a `PAT` to the action (the permission to create a Check). tbh, I personally wouldn't deactivate the checks. I think I'd rather renounce to the check summary in the GH Actions section (nr. 4), but still not sure if that is worth it...  To be completely honest, the background to this query was that the comment on the PR is authored by `github-actions-bot`  and I wanted to use a technical user for it here:
![image](https://user-images.githubusercontent.com/108832394/184529640-d5521700-95e7-498a-a46d-881f445693e2.png)

which is I think the original reason for #80 ... but as I said, if this comes with some caveats, such as losing the check  in the checks section or the check summary in the `Actions` tab, then I would think it twice.. anyhow, if you come up with some cool idea, I'd happily use it, otherwise continue with the current `v2`. Thanks again for your work!
Cheers,
Rodrigo
