### ISSUE TITLE
Multiple test results

### ISSUE THREAD

**Issue by asztalosdani** [EnricoMi/publish-unit-test-result-action#350]
Is it possible to have multiple test results for a single PR/commit?

I have a repository where the tests are grouped into a few separate sections, e.g. `core-tests`, `unreal-tests`, `maya-tests`. These are run separately, and I would like to see the results separately as well. If I just naively run my `unreal-tests`, the comment says, all my `core-tests` are removed, and lists all `unreal-tests` as new.

**Comment by EnricoMi** [comment]
Yes, run the action once per section, each with a different value for `check_name`.

**Comment by asztalosdani** [comment]
Awesome, thank you! It works, and is exactly what I wanted. Would be cool to have it documented (unless it is there, and I just missed it...)

**Comment by EnricoMi** [comment]
You are right, it is not explicitly mentioned what special role `check_name` has when running the action multiple times per commit. I will improve that.

**Comment by MarkOSullivan94** [comment]
@EnricoMi is there a way to combine multiple test results into one comment instead of having a separate comment per test group result?

**Comment by EnricoMi** [comment]
Sure, run the action once over all test result files.
