### ISSUE TITLE
Test result deltas missing for fork pull requests

### ISSUE THREAD

**Issue by laeubi** [EnricoMi/publish-unit-test-result-action#359]
It would be good to have an option like "compare_with" where I can give a branch (e.g. master) and then each PR gets infos added if test are added/removed through this PR, there are more ingored or failing test and so on.

**Comment by EnricoMi** [comment]
I don't really get the difference to the current behaviour. Can you give a more detailed example, and where that is different to what you can do already? Thanks!

**Comment by laeubi** [comment]
Actually I'd like to have something like this:

https://github.com/EnricoMi/publish-unit-test-result-action/blob/master/misc/github-pull-request-comment.png

but this seems only working if it is run as the same job, I currently use the approach described here:

https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches

in such a case I not see this +/- and I assumed this is because the action don't know the actual commit, so the idea as that in such a case it could simply use a fixed ref (like master) to compare against?

**Comment by EnricoMi** [comment]
That should work for forks. Is your repo public? Can you share the YAML file and a log, preferably with `log_level: DEBUG`?

**Comment by laeubi** [comment]
> That should work for forks. Is your repo public? Can you share the YAML file and a log, preferably with `log_level: DEBUG`?

I have created a build where I delete a test here:
https://github.com/eclipse-tycho/tycho/pull/1520#issuecomment-1276620400

**Comment by EnricoMi** [comment]
It looks like you are missing step 1 (event file), see "Step-by-step instructions" in https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches.

Also these input arguments are needed:

    event_file: artifacts/Event File/event.json
    event_name: ${{ github.event.workflow_run.event }}

**Comment by laeubi** [comment]
Thanks I'll check this, it seems we have not carefully adjusted this action when upgrading from v1 > v2 and I missed the collapsed code example :-\

**Comment by laeubi** [comment]
This works now great! :+1: 

https://github.com/eclipse-tycho/tycho/pull/1520

Its a bit cumbersome to setup, but I think that's because of how github works here
