### ISSUE TITLE
Fix Deprecating save-state and set-output commands

### ISSUE THREAD

**Issue by ktasper** [EnricoMi/publish-unit-test-result-action#363]
As per [Github's Annocument](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) this repo should be updated to use:
```
- name: Save state
  run: echo "{name}={value}" >> $GITHUB_STATE

- name: Set output
  run: echo "{name}={value}" >> $GITHUB_OUTPUT
```

Instead of the derepecating:

```
- name: Save state
  run: echo "::save-state name={name}::{value}"

- name: Set output
  run: echo "::set-output name={name}::{value}"
```

[I have a PR for this here](https://github.com/EnricoMi/publish-unit-test-result-action/pull/362)

**Comment by EnricoMi** [comment]
Merged, thanks for raising this.
