### ISSUE TITLE
Make action comment on Pull Requests once and edit

### ISSUE THREAD

**Issue by EnricoMi** [EnricoMi/publish-unit-test-result-action#38]
In https://github.com/EnricoMi/publish-unit-test-result-action/issues/28#issuecomment-710080411 we have discussed that the action should allow to configure it commenting on PRs only once and later edit that comment with latest test results. Then, the test results stay at the top of the PR (always at the same position) and the PR does not fill up with more and more test result comments.

**Comment by simonsabin** [comment]
I'd go for this one

**Comment by EnricoMi** [comment]
Implemented in #128, to be released soon.
