### ISSUE TITLE
issue on populating the .trx results

### ISSUE THREAD

**Issue by Puvvada-Ananth** [EnricoMi/publish-unit-test-result-action#388]
Hello @EnricoMi 

I am seeing following error that, after the build job is completed the results which are being populated are not matching our count that may be number of Test cases(passed, failed and skipped), execution time etc., can you help me on it ?
The actuals are as follows:
**Total number of test cases - 646 (Passed-461,Failed-185,skipped-0)
Total time taken to execute is - 34 min 51 Sec**
But if you see the results populated form **publish-unit-test-result-action** are no where matching it, Could you help me in understanding this if i am missing anything.

![image](https://user-images.githubusercontent.com/106600556/209296747-8c595e8a-6ac8-4111-ab02-8310aebc4603.png)

**Comment by EnricoMi** [comment]
Could you please provide the XML test result files? That would help.

**Comment by Puvvada-Ananth** [comment]
Sure i will try it

**Comment by Puvvada-Ananth** [comment]
Hi @EnricoMi 
We do not any option to generate the results in .xml the only option we have for dotnet test command is .trx.
Also most of the times the test results are not populating in jobs pan as attached screenshot. sometimes it is populating and some time i have to go to the job from the build output and see them which is not an ideal scenario if we are using your action.
As below we are using this action, am i missing anything to include in the actions. Could you please help me in achieving the required things. 
  - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          trx_files: "<Path of the file>"

<img width="289" alt="image" src="https://user-images.githubusercontent.com/106600556/211751104-df7d3a65-afe4-4cc0-a21b-92e6c48cd196.png">

**Comment by EnricoMi** [comment]
I doubt `trx_files: ""` will ever populate any results.

**Comment by Puvvada-Ananth** [comment]
but it is populating surprisingly. let me try with out it once.

**Comment by Puvvada-Ananth** [comment]
@EnricoMi 
No change same again.

**Comment by EnricoMi** [comment]
Alright, I need the workflow yaml code used, the full log output of the action, and all TRX files to be processed by the action. Otherwise, there is nothing I can do with just the input given above.

Please run the action with:
```
with:
  root_log_level: DEBUG
  log_level: DEBUG
```
