### ISSUE TITLE
Make action reduce number of comments on PR

### ISSUE THREAD

**Issue by EnricoMi** [EnricoMi/publish-unit-test-result-action#39]
On https://github.com/EnricoMi/publish-unit-test-result-action/issues/28#issuecomment-710080411 we have discussed that the action could reduce the number of comments that it creates by reusing its latest comment until other comments are added by other users. This way, the unit test results stay at the end of the PR conversation, but not every commit causes a new comment. This is an alternative behaviour between only commenting once (#38) and always commenting, the current behaviour. This could be combined with hiding older comments (#36).

**Comment by revmischa** [comment]
IMO just edit the existing comment, I don't think it needs to go at the end of the PR. It will just create email notif noise.

**Comment by EnricoMi** [comment]
I agree, I think this is the most useful behaviour in addition to the current behaviour. And reducing e-mail noise is a good plus (if updates really do not trigger e-mails as well). Will prioritize #38 over the others.

**Comment by EnricoMi** [comment]
Feature #38 has been implemented, closing this.
