### ISSUE TITLE
Make action only comment on Pull Request if there are failures, errors or more skips

### ISSUE THREAD

**Issue by EnricoMi** [EnricoMi/publish-unit-test-result-action#41]
The action should allow to configure it to only comment on the PR if there are any useful information in the test results, i.e. there exist failures, errors or the number of skipped tests increase w.r.t. to the earlier commit. The first run compares to the base.

**Comment by EnricoMi** [comment]
Given the action now creates only a single comment, which is updated on subsequent runs, the feature described here is less of value. What do you think? Any good arguments for keeping this issue open?

**Comment by itungnt** [comment]
I used Github notification and would like to only receive the notification when there is test fails

**Comment by remmelt** [comment]
I would find this very helpful still: we run a matrix of 20+ test runs per PR, so this gets out of hand very quickly.

**Comment by EnricoMi** [comment]
Can you upload test results from each of these 20+ runs and run the publish action once on all test result artifacts / files? If not, what prevents you from that?

**Comment by EnricoMi** [comment]
> I used Github notification and would like to only receive the notification when there is test fails

No notification could also mean that publish check did not run. But from the check that the publish action itself succeeded you see tests have been analysed. If that action fails, you would get notified for that. So I think it is safe to disable the comment in that case. Will look into this.

**Comment by EnricoMi** [comment]
This has just been released. Enjoy!
