### ISSUE TITLE
Unable to Pull Docker Image

### ISSUE THREAD

**Issue by nimshi89** [EnricoMi/publish-unit-test-result-action#412]
We're getting an error when trying to use this action in our repository. The error we're getting is: `Unable to find image 'ghcr.io/enricomi/publish-unit-test-result-action:v2.4.2' locally`
Link to the repository:  `https://github.com/GSS-Cogs/csvcubed/actions/runs/4304238102/jobs/7505066858#step:5:27`

When we go to the <https://ghcr.io/v2/enricomi/publish-unit-test-result-action/manifests/v2.4.2> link in a browser we get an HTTP 401 response with the following message:

```
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required"}]}
```

Is there some problem with the permissions on the docker image used in the main action at all?

**Comment by EnricoMi** [comment]
The log says:

       received unexpected HTTP status: 503 Service Unavailable

So the Github registry is currently not available.

Check githubstatus.com for more details: https://www.githubstatus.com/incidents/bypf7bqdh4g0

**Comment by EnricoMi** [comment]
Incident has been resolved.
