### ISSUE TITLE
Comment hard codes "Unit Test Results" instead of $check_name

### ISSUE THREAD

**Issue by spookylukey** [EnricoMi/publish-unit-test-result-action#42]
See https://github.com/EnricoMi/publish-unit-test-result-action/blob/de7f7f0c5f7694846ce69e3384f2e5a03253c141/publish_unit_test_results.py#L629

I was expecting to find the defined `check_name` used here.

The result is if you have more than one instance of this action in use (e.g. for "Integration tests" and "Unit tests"), they both get the same text in the comment and you can't easily tell which is which.

I'm happy to provide a PR for this if it is accepted.

**Comment by EnricoMi** [comment]
Thanks for raising this, it is a good use case to justify making the comment title configurable. There is PR #33 which is already fixing this.

**Comment by EnricoMi** [comment]
Please test master, if this fixes the issue for you.

**Comment by spookylukey** [comment]
Works perfect, thanks!
