### ISSUE TITLE
Add test time to case annotations

### ISSUE THREAD

**Issue by Axel-Naumann** [EnricoMi/publish-unit-test-result-action#431]
Thank you so much for providing a super useful ingredient to GH Actions!

We are sometimes suffering from test timeouts and those are hard to read off the current annotations: it'd be great to see the `time` field as provided by xunit.

It seems that I'd need to add this to https://github.com/EnricoMi/publish-unit-test-result-action/blob/8a733d3602488f6d25671ff71e1ff89595504b9c/python/publish/junit.py#L251 - is that correct? It might be way simpler for you to implement that yourself rather than you guiding me... but I can understand if you say "go provide me with a PR" :-)

**Comment by EnricoMi** [comment]
You mean annotations like this should contain the time taken by the failing tests?
![image](https://user-images.githubusercontent.com/44700269/227608428-65a1613a-dffe-477a-86cf-5f1fd4147cad.png)

**Comment by EnricoMi** [comment]
Or one of these: https://github.com/root-project/root/runs/12259512624
![image](https://user-images.githubusercontent.com/44700269/227610293-1c73d89b-dd5c-40fe-b18e-bdad1ab0f366.png)

CERN is using my action, I am flattered!

**Comment by EnricoMi** [comment]
One could add the time for each test run behind the file that reports the test run:

    artifacts/Test Results ubuntu22 Debug/TestResults.xml (took 123s)

That even helps to find the file with the long running test.

**Comment by Axel-Naumann** [comment]
Yeah exactly, that'd be super nice to have!

Look, your work here is super useful, no wonder we at CERN use it! :-)

**Comment by EnricoMi** [comment]
Let me sketch something out...

**Comment by Axel-Naumann** [comment]
...and (independently) if you're ever in the Geneva Switzerland area please ping me :-) Just as a little "thank you" from open source to open source for your excellent work!

**Comment by EnricoMi** [comment]
Fixed in #439.

Please test via:

    uses: EnricoMi/publish-unit-test-result-action/composite@branch-test-time-in-case-annotation

**Comment by Axel-Naumann** [comment]
I thought I'd see those at https://github.com/root-project/root/runs/12780818631 - is there an option I need to set? Do you expect [the change](https://github.com/root-project/root/pull/12663/files) to trigger this?

**Comment by EnricoMi** [comment]
That change would enable showing the times, but it has to be in master in order to work.

I will merge this any way soon.
