### ISSUE TITLE
Issue with report

### ISSUE THREAD

**Issue by recur-kartikeya** [EnricoMi/publish-unit-test-result-action#435]
I am getting this error : Error: RuntimeError: Unsupported file format: coverage/test-reporter.xml

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/121946693/228464003-549ab7a9-77a0-4430-bb33-6a111253b557.png">

**Comment by EnricoMi** [comment]
I think this is not a test result XML file but a test coverage XML file.

How do you generate that file?

**Comment by recur-kartikeya** [comment]
Thanks for responding, I am using this command : npm run test -- --coverage

**Comment by EnricoMi** [comment]
There should be another XML file being created.

**Comment by EnricoMi** [comment]
Follow the link from the README.md: https://github.com/EnricoMi/publish-unit-test-result-action#generating-test-result-files

**Comment by EnricoMi** [comment]
Any luck?

**Comment by EnricoMi** [comment]
Please reopen if you have any further questions.
