### ISSUE TITLE
Unable to find PR on push event

### ISSUE THREAD

**Issue by ggreco** [EnricoMi/publish-unit-test-result-action#437]
It seems that the action is not able to find the PR to add the comment to if it's executed in a script that runs on a `push` event and not on a `pull_request event`:

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/1829939/230592944-36d4e7c3-2ef7-4131-8cfc-6ec56a264e7e.png">

 I had similar problems with https://github.com/platisd/clang-tidy-pr-comments but that action has an additional parameter to specify the PR is running on, and, from a commit, it's possible to get the PR using for instance:
 
 https://github.com/jwalton/gh-find-current-pr
 
 I suggest, if possible to add a `pull_request_id` option to be used as target PR when the action silently fail with `There is no pull request for commit XYZ` like in the provided screenshot.

**Comment by EnricoMi** [comment]
Yes, when there is no pull request given in the event (given for `pull_request` events), than the action should fall back to the commit's pull requests. Will revert behaviour change from v2.6.1 and add this fall back. See #438.

**Comment by ggreco** [comment]
BTW looking at the source code I found the option `search_pull_request` (undocumented in README.md) and setting that to `true` I've been able to get the comment published/updated in the PR.

**Comment by ggreco** [comment]
I can confirm it to work properly now also without `search_pull_request`, thanks!

**Comment by EnricoMi** [comment]
Awesome, thanks for testing!
