### ISSUE TITLE
Fork repositories can still utilize the job summary

### ISSUE THREAD

**Issue by infogulch** [EnricoMi/publish-unit-test-result-action#440]
When this action runs on a fork repository it outputs this warning:

> This action is running on a pull_request event for a fork repository. It cannot do anything useful like creating check runs or pull request comments. To run the action on fork repository pull requests, see ...

In my particular case, I'm not interested in creating check runs or pull request comments (those features are disabled), I'm mostly interested in the nice job summary that your action creates.

* Does the action have enough access to generate and produce this job summary even in a PR from a fork repository?
* If so, would you consider loosening this rule to produce the job summary even in a fork repository PR context?
* Otherwise are you aware of a different unit test to 'job summarizer' action or script I could use?

Link to run: https://github.com/mthom/scryer-prolog/actions/runs/4684185489/jobs/8300064413?pr=1783#step:11:31

**Comment by EnricoMi** [comment]
Good point, this should work. I will loosen this restriction.

**Comment by infogulch** [comment]
Could you have it omit the warning as well?

Maybe it could make sense to only send the warning if it tries to use one of the features for which it lacks permissions.

**Comment by EnricoMi** [comment]
Please test this new feature:

```yaml
uses: EnricoMi/publish-unit-test-result-action/composite@branch-publish-summary-on-fork
```

**Comment by infogulch** [comment]
It seems to work great!

https://github.com/mthom/scryer-prolog/actions/runs/4692356844#summary-12730746549

**Comment by EnricoMi** [comment]
> It seems to work great!

Awesome!

Can you rerun the [`build-test (ubuntu-20.04, stable, bash, true)` job](https://github.com/mthom/scryer-prolog/actions/runs/4692356844/jobs/8317978297#logs) please?

**Comment by EnricoMi** [comment]
Can you remove the `comment_mode: off` option? I want to see how the info logging looks like. Hard to test otherwise.

**Comment by infogulch** [comment]
The "fork repo PR" build, which fails of course: https://github.com/mthom/scryer-prolog/actions/runs/4693217622/jobs/8319908277?pr=1783

My own PR on my own repo, which succeeds: https://github.com/infogulch/scryer-prolog/pull/1#issuecomment-1507528415

**Comment by EnricoMi** [comment]
It did not pick up the latest commit...

    Download action repository 'EnricoMi/publish-unit-test-result-action@branch-publish-summary-on-fork' (SHA:1204b1f36fc0e1f891ecf33c85d74923a83b712f)
https://github.com/mthom/scryer-prolog/actions/runs/4693217622/jobs/8319908277#step:1:40

The SHA should be `0d603d0773e2b8cae05c20c58f26741ab36cd410`.

**Comment by infogulch** [comment]
How about now: https://github.com/mthom/scryer-prolog/actions/runs/4693740215/jobs/8321109382?pr=1783#step:10:202

> comment_mode: always
> ...
>   2023-04-13 21:01:38 +0000 - publish -  INFO - Commenting on pull requests disabled

Compare my own repo: https://github.com/infogulch/scryer-prolog/actions/runs/4693740257/jobs/8321109514#step:10:202

> comment_mode: always
> ...
>   2023-04-13 21:01:41 +0000 - publish -  INFO - Edited comment for pull request #1: https://github.com/infogulch/scryer-prolog/pull/1#issuecomment-1507528415

**Comment by EnricoMi** [comment]
Looks good, thanks for reporting and testing!

**Comment by EnricoMi** [comment]
With

    uses: EnricoMi/publish-unit-test-result-action@v2

you run the action from a pre-built Docker image.

With

    uses: EnricoMi/publish-unit-test-result-action/composite@v2

you run the action from sources, which takes longer to start up.

Windows and macOS runners do not support Docker containers, so they require to run the composite action. In addition, the composite action is used to run the action from branches (testing).

**Comment by infogulch** [comment]
Oh I see. Have you considered using https://github.com/actions/cache to reduce the startup time for the composite action?

**Comment by EnricoMi** [comment]
Caching pip packages is employed by the composite action:

https://github.com/EnricoMi/publish-unit-test-result-action/blob/8f1514555327b76a973605d259890793e7d34c5d/composite/action.yml#L182-L188

**Comment by EnricoMi** [comment]
T

> I don't quite understand, what do you mean by this? Does the root action call the composite action if run on a branch, or is the workflow author expected to use the composite action in this case?

The latter, via the composite action it is possible to run the action from any branch or commit. This is not possible via the root action. This is only relevant for me testing my action, as I have asked you in https://github.com/EnricoMi/publish-unit-test-result-action/issues/440#issuecomment-1507391791.

**Comment by infogulch** [comment]
Ok. So you would expect a CI workflow like the one I linked before [^1] to use the `EnricoMi/publish-unit-test-result-action/composite@v2` action, not the root action.

[^1]: https://github.com/mthom/scryer-prolog/actions/runs/4703416387#summary-12761548785

**Comment by EnricoMi** [comment]
Since it is running on all three OS, use the composite action:

    uses: EnricoMi/publish-unit-test-result-action/composite@v2

**Comment by infogulch** [comment]
Thank you for your patience to answer all of my questions!
