### ISSUE TITLE
Use dawidd6/action-download-artifact@v2 in docs for forked repos

### ISSUE THREAD

**Issue by uli-f** [EnricoMi/publish-unit-test-result-action#445]
This is more a question / feature request than an issue, apologies if this is the wrong place to raise this.

I very much appreciate this github actions and its comprehensive and well-laid out documentation is one of the reasons.

To make this action work for pull requests created by Dependabot I follow the instructions in the section [Support fork repositories and dependabot branches](https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches) which works seamlessly.

I recently stumbled upon the github action [dawidd6/action-download-artifact@v2](https://github.com/dawidd6/action-download-artifact). Could this be a potential replacement for the code that currently sits in the step `Download and Extract Artifacts` of the documentation in the section [Support fork repositories and dependabot branches](https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches)? If so, adding this to the documentation with an example would be great 😃

**Comment by EnricoMi** [comment]
I am currently evaluating that action and I plan to use it in the section. Thanks for the pointer!
