### ISSUE TITLE
Provide a configuration that allows to cluster different tests for each os target 

### ISSUE THREAD

**Issue by asilverman** [EnricoMi/publish-unit-test-result-action#458]
## Description

First of all I'd like to thank you for your efforts building this excellent tool. in my case I am trying to report the results of tests that are executing on different target platforms (linux-x64, osx-64, win-x64), see here for the pipeline https://github.com/Azure/bicep/pull/10826/files.

I am using a fan out strategy to distribute the execution of the tests on separate runners, due to idiosyncrasies of the `dotnet` executable I am forced to use test filters to select the test that need to be executed, As a consequence the net, my test results contain a bunch of `.trx` files that don't run any tests.

In addition, I noticed that the results in the comment aggregate all of the trx files together and I want the output to be sliced by target platform, that is one set of results of win-x64, another for linux-x64, etc...

How can I achieve this?

![image](https://github.com/EnricoMi/publish-unit-test-result-action/assets/9611108/15ad6957-fb17-4a35-8960-6c36164723ef)

Link to my repo: https://github.com/Azure/bicep/pull/10826

**Comment by EnricoMi** [comment]
Run it multiple times with differing `check_name` values: https://github.com/Azure/bicep/pull/10826/files#r1207142333

**Comment by asilverman** [comment]
Nice!! Thank you for that insight, a suggestion would be to add this to the docs, that way people have a clear understanding of how to use it for this kind of use case ❤️❤️❤️

**Comment by asilverman** [comment]
it does, thanks!
