### ISSUE TITLE
Can't run on windows with python 3.11>> because lxml fails to build

### ISSUE THREAD

**Issue by TCatshoek** [EnricoMi/publish-unit-test-result-action#492]
Hi there! 

Just wanted to report an issue running this action on windows with python versions 3.11 or greater. 

There appears to be no pre-built package for lxml 4.9.1 for these versions of python, so it falls back to a source build which fails with the following error:

```
    C:\Users\runneradmin\AppData\Local\Temp\pip-install-mjpb3dnp\lxml_45bbd1db508e4fd98d76804d8e1e9ffa\src\lxml\includes/etree_defs.h(14): fatal error C1083: Cannot open include file: 'libxml/xmlversion.h': No such file or directory
    Compile failed: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
```

Looks like lxml versions > 4.9.1 have pre built packages for 3.11 so bumping the version number of this dependency should be enough to fix it if no other issues pop up.

**Comment by EnricoMi** [comment]
Thanks for reporting, fixed in #387. Will cut a new release soon.

**Comment by TCatshoek** [comment]
Awesome, thank you!

**Comment by EnricoMi** [comment]
This has been released.
