### ISSUE TITLE
Getting error "  CData section too big found, line 357183, column 7 (TESTS-TestSuites.xml, line 357183)"

### ISSUE THREAD

**Issue by nikhilyedke1995** [EnricoMi/publish-unit-test-result-action#509]
I'm using github action "EnricoMi/publish-unit-test-result-action/composite@v2" to publish test results, but getting error "CData section too big found, line 357183, column 7 (TESTS-TestSuites.xml, line 357183)". Any workaround this?

**Comment by EnricoMi** [comment]
Try `large_files: true`.

**Comment by nikhilyedke1995** [comment]
Thanks!! It Worked.
