### ISSUE TITLE
Publish test results task is not working due to test result XML not being found

### ISSUE THREAD

**Issue by mmowry-accuity** [EnricoMi/publish-unit-test-result-action#518]
We have the following tasks in our actions workflow:

```
      - name: Print Directory
        run: |
          ls -al /home/testresults
          ls -al /home
          ls -al /home/testresults/test-output
          ls -al /home/testresults/test-output/junitreports
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
            files: |
              /home/testresults/test-output/testng-results.xml
              /home/testresults/test-output/junitreports/testjunit-results.xml
```

The Print Directory task is confirming that both of the test results xml files are present as expected. However the task logs indicate that the xml test results files weren't processed. What are we missing? We have (1) checked permissions, (2) tried different file names, and (3) tried using a wildcard. I was thinking perhaps our xml results format was an issue, but the warning indicates that the files can't even be found. We would appreciate any help with this issue. Thanks in advance!

`2023-10-10 21:53:51 +0000 - publish - WARNING - Could not find any files for /home/testresults/test-output/testng-results.xml, /home/testresults/test-output/junitreports/testunit-results.xml`

**Comment by EnricoMi** [comment]
Duplicates #353.

I have just added some notes on absolute paths here: https://github.com/EnricoMi/publish-unit-test-result-action#running-with-absolute-paths

**Comment by mmowry-accuity** [comment]
Thank you for the reply, that response got us up and running and thanks for adding the documentation.
