### ISSUE TITLE
Test Results are not shown in workflow run job list 

### ISSUE THREAD

**Issue by dvag-dzenan-softic** [EnricoMi/publish-unit-test-result-action#529]
Hello,

as we update to v.2.11.0, test results are not shown in workflow run summary job list on the left. 

It worked fine with v2.10.0.

Examples: 

**v2.11.0**
![image](https://github.com/EnricoMi/publish-unit-test-result-action/assets/93660303/ef49580e-722f-4687-a728-b831f6e74385)

**v2.10.0**
![image](https://github.com/EnricoMi/publish-unit-test-result-action/assets/93660303/2ff94992-4d67-4b28-938b-9dec064477bd)

Is this an expected behavior?

Thanks,
Dzenan

**Comment by EnricoMi** [comment]
Did you introduce other workflows while upgrading to v2.11.0? The test results might end up at some other workflow that ran on the same commit. See #12.

**Comment by dvag-dzenan-softic** [comment]
No i didnt introduce other workflows.

**Comment by dvag-dzenan-softic** [comment]
Hi, do you have any other idea what could cause this problem? Here you can see a all jobs and there subjobs 

![image](https://github.com/EnricoMi/publish-unit-test-result-action/assets/93660303/68c0bdbb-37a7-4fed-a6c2-f13fea97491e)

The Test Results are shown under the annotations block 

![image](https://github.com/EnricoMi/publish-unit-test-result-action/assets/93660303/6d8839da-a358-41f7-a4f4-e6c955814bb6)

**Comment by EnricoMi** [comment]
Can you provide the log of one of the runs of this action?

**Comment by dvag-dzenan-softic** [comment]
![image](https://github.com/EnricoMi/publish-unit-test-result-action/assets/93660303/01a04fc1-9994-4368-91f3-2ddb2c1bb836)

**Comment by dvag-dzenan-softic** [comment]
In a different run of the same workflow. The run number shown above is 20 and the results are in run number 19

**Comment by dvag-dzenan-softic** [comment]
Can you work with this information or do you need more informations? Its an important topic for us because we might have to downgrade to an older version.

**Comment by dvag-dzenan-softic** [comment]
Ok, but why does it work with an older version?

**Comment by EnricoMi** [comment]
Did you have multiple events for your workflow before?

Did each workflow run for one commit have the checks before?

Do both events fire simultaneously (`push` and `sync`) or at different times (`sync` and `schedule`)?

**Comment by dvag-dzenan-softic** [comment]
No, i only changed the version to 2.11.0.

**Comment by EnricoMi** [comment]
Sorry, I cannot help if you don't answer those three questions specifically.

**Comment by dvag-dzenan-softic** [comment]
Ah, I saw now that I added new events for testing purpose i forgot about. I removed the events and now it works fine. 
Thanks for your time and help :)

**Comment by EnricoMi** [comment]
Just as I suspected. Glad I could help.
