### ISSUE TITLE
Remove symbols links

### ISSUE THREAD

**Issue by ranrsg** [EnricoMi/publish-unit-test-result-action#534]
Currently the symbols links (in the test result PR comment/other locations) are pointing to the action repository [README ](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v2.11.0/README.md#the-symbols) which cause a bit confuse.
![image](https://github.com/EnricoMi/publish-unit-test-result-action/assets/125865943/3428ab4c-0619-4901-951f-181231f6d48e)

How can I disable these symbols links?

**Comment by EnricoMi** [comment]
Looks like Github has changed their rendering of markdown. I agree, this looks ugly. I will remove the links.

**Comment by EnricoMi** [comment]
Change has been released: https://github.com/EnricoMi/publish-unit-test-result-action/releases/tag/v2.12.0
