### ISSUE TITLE
Option "check_run" not recognized

### ISSUE THREAD

**Issue by markusroessler** [EnricoMi/publish-unit-test-result-action#546]
the documented option "check_run" doesn't seem to work. Using it emits to the following warning message:

`Unexpected input(s) 'check_run', valid inputs are ['entryPoint', 'args', 'github_token', 'github_token_actor', 'github_retries', 'commit', 'check_name', 'comment_title', 'comment_mode', 'fail_on', 'action_fail', 'action_fail_on_inconclusive', 'files', 'junit_files', 'nunit_files', 'xunit_files', 'trx_files', 'time_unit', 'test_file_prefix', 'report_individual_runs', 'report_suite_logs', 'deduplicate_classes_by_file_name', 'large_files', 'ignore_runs', 'job_summary', 'compare_to_earlier_commit', 'pull_request_build', 'event_file', 'event_name', 'test_changes_limit', 'check_run_annotations', 'check_run_annotations_branch', 'seconds_between_github_reads', 'seconds_between_github_writes', 'secondary_rate_limit_wait_seconds', 'json_file', 'json_thousands_separator', 'json_suite_details', 'json_test_case_results', 'search_pull_requests']`

Version: 2.11.0

Edit: Is there any other way to disable check runs?

**Comment by EnricoMi** [comment]
This feature has not been released yet, you are looking at the README.md of master branch. This will be released this week.

**Comment by markusroessler** [comment]
ah ok my bad, thank you for the info

**Comment by EnricoMi** [comment]
This has been released: https://github.com/EnricoMi/publish-unit-test-result-action/releases/tag/v2.12.0
