### ISSUE TITLE
Publishing json file doesn't work if check_run is set to false

### ISSUE THREAD

**Issue by ebbeknudsen** [EnricoMi/publish-unit-test-result-action#554]
I don't see why we shouldn't be able to create the json file, if `json_file` is set

`check_run` doesn't publish to the correct workflow in our case, so we cannot use it. However, we would still like to be able to use the summary and the json report.

I could be open for creating a PR if that is acceptable? A quick look at the code suggests that the change should be pretty straightforward

**Comment by EnricoMi** [comment]
Yes, please go ahead.

**Comment by ebbeknudsen** [comment]
> Yes, please go ahead.

PR: https://github.com/EnricoMi/publish-unit-test-result-action/pull/555
