### ISSUE TITLE
androidTest / Could not find any files for test-results/**/*.xml

### ISSUE THREAD

**Issue by johnjohndoe** [EnricoMi/publish-unit-test-result-action#564]
# Context
I like to see test results both for unit and instrumentation tests for my [Android application project](https://github.com/EventFahrplan/EventFahrplan). It contains a few different Gradle modules (android application, android library, kotlin library) and tests in the `test` and `androidTest` source sets. Also, it contains multiple product flavors.
Here is the workflow configuration: [7760612891/workflow](https://github.com/EventFahrplan/EventFahrplan/actions/runs/7760612891/workflow)

# Current state
Test results for unit tests (`test` source set) are written to the respective module `build/test-results/` folders, e.g. `app/build/test-results/testCcc37c3DebugUnitTest/TEST-nerd.tuxmobil.fahrplan.congress.alarms.AlarmServicesTest.xml`. These XML files are then correctly picked up by the `publish-unit-test-result-action`.

![image](https://github.com/EnricoMi/publish-unit-test-result-action/assets/144518/72856992-0bb3-48fc-8573-d3bad3ba7391)

Test results for instrumentation tests (`androidTest` source set) seem to be **missing** and therefore are **not** picked up.

> Could not find any files for test-results/**/*.xml

![image](https://github.com/EnricoMi/publish-unit-test-result-action/assets/144518/983a7870-9566-4a21-8b1e-5899939106ce)

The instrumentation tests are part of the `database` module. They do not target UI but still need the Android framework to run. See: [database/androidTest](https://github.com/EventFahrplan/EventFahrplan/tree/master/database/src/androidTest/java/info/metadude/android/eventfahrplan/database/extensions)

# Related
- https://github.com/EnricoMi/publish-unit-test-result-action/issues/119
- https://github.com/EnricoMi/publish-unit-test-result-action/issues/518
- https://github.com/EnricoMi/publish-unit-test-result-action/issues/424

**Comment by EnricoMi** [comment]
Invoking the publish action twice requires individual `check_name` values, e.g.
- the `build` job should use `check_name: 'Test Results (build)`
- the `android_tests` job should use `check_name: 'Test Results (instrumentation)`

Regarding the missing test results: your `File listing` step shows there are no `TEST*.xml` files in path `.`:
```
find . -name "TEST*.xml"
echo "All files:"
find .
```
There are no files listed before `All files`:
```
All files:
.
```

**Comment by johnjohndoe** [comment]
I added the `check_name` option now, see [runs/7769998601](https://github.com/EventFahrplan/EventFahrplan/actions/runs/7769998601).

> Further, there is no `test-results` directory in `.`, so `test-results/**/*.xml` cannot find anything.

Do you know why the xml files are missing?

**Comment by EnricoMi** [comment]
No idea, seems unrelated to this action, maybe you should check with https://github.com/reactivecircus/android-emulator-runner.

**Comment by johnjohndoe** [comment]
OK. If you see no errors in the configuration for this action then you can close this issue. Thank you.

**Comment by johnjohndoe** [comment]
I fixed running the instrumentation tests now and I can see an xml file being generated. See [runs/7773831930](https://github.com/EventFahrplan/EventFahrplan/actions/runs/7773831930). It isn't picked up by the results action, though.

**Comment by EnricoMi** [comment]
Because `androidTest-results/**/*.xml` and `*/androidTest-results/**/*.xml` cannot match `./database/build/outputs/androidTest-results/connected/TEST-test(AVD) - 10-_database-.xml`.

Try `**/androidTest-results/**/*.xml` instead.
