### ISSUE TITLE
Windows requirements.txt fail

### ISSUE THREAD

**Issue by jeffcoffee** [EnricoMi/publish-unit-test-result-action#580]
https://github.com/EnricoMi/publish-unit-test-result-action/blob/e22cb89252eed6924b77cf94ec9d7776e0d2bc0d/windows/action.yml#L234

Replace
$env.GITHUB_ACTION_PATH
with
$env:GITHUB_ACTION_PATH

Thanks

**Comment by EnricoMi** [comment]
Thanks for reporting, fixing asap.

**Comment by EnricoMi** [comment]
Fix has been released. Thanks for reporting and investigating!
