### ISSUE TITLE
Annotations are reported at line 0 and therefore are not display correctly.

### ISSUE THREAD

**Issue by SoggyBottomBoy** [EnricoMi/publish-unit-test-result-action#591]
I'm unsure of the exact behavior to expect, but annotations appear to always be set at line 0 meaning they do not show up on the file. Is this intended?

![image](https://github.com/EnricoMi/publish-unit-test-result-action/assets/36346832/eb06aff9-ba11-4040-bc5c-b67ca1dc5c6e)

Clicking `see this annotation in the file changed` doesn't actually display it. But maybe this is the intent? The file I changed caused the test to fail whilst the annotation appears to refer to the test file, because the test file was not changed it is not part of the commit.

**Comment by EnricoMi** [comment]
Can you confirm the `trx` file contains line information?

**Comment by SoggyBottomBoy** [comment]
Ah no it appears your correct, line information is not contained within trx files.

**Comment by EnricoMi** [comment]
Looks like there is nothing the action can do about this then. Please reopen if needed.
