### ISSUE TITLE
Windows PowerShelll action fails with "invalid syntax"

### ISSUE THREAD

**Issue by EnricoMi** [EnricoMi/publish-unit-test-result-action#602]
@matteo-savore-deltatre [reported](https://github.com/EnricoMi/publish-unit-test-result-action/issues/586#issuecomment-2129364266):

![image](https://github.com/EnricoMi/publish-unit-test-result-action/assets/1515441/a7669244-a16d-4b3a-a969-0f394d5f4a54)

**Comment by matteo-savore-deltatre** [comment]
now works , thanks

**Comment by EnricoMi** [comment]
@matteo-savore-deltatre with `"now"` you mean the fix works?

    uses: EnricoMi/publish-unit-test-result-action/windows@windows-avoid-escaped-quotes

or the latest release works?

    uses: EnricoMi/publish-unit-test-result-action/windows@v2

**Comment by matteo-savore-deltatre** [comment]
> @matteo-savore-deltatre with `"now"` you mean the fix works?
> 
> ```
> uses: EnricoMi/publish-unit-test-result-action/windows@windows-avoid-escaped-quotes
> ```
> 
> or the latest release works?
> 
> ```
> uses: EnricoMi/publish-unit-test-result-action/windows@v2
> ```

the fix, thanks

(apologies but i missed the message)

**Comment by EnricoMi** [comment]
Thanks for the reply. The fix has been merged to master (so that branch disappeared), and will be released soon, so the fix will be available via `v2`.

**Comment by EnricoMi** [comment]
The fix has been released.
