### ISSUE TITLE
Option fail_on is not respected 

### ISSUE THREAD

**Issue by LorenzoBettini** [EnricoMi/publish-unit-test-result-action#618]
I specified `fail_on: nothing` in our workflow (due to flakes not currently handled) but the action still marks the PR as failed.

See https://github.com/eclipse/xtext/pull/3164

Am I missing something?

**Comment by EnricoMi** [comment]
https://github.com/eclipse/xtext/pull/3164#issuecomment-2301171013

**Comment by LorenzoBettini** [comment]
@EnricoMi sorry I forgot to close this myself. After merging the test results job does not fail.

Of course, that's a temporary workaround, waiting for flaky tests to be officially supported ;)
