### ISSUE TITLE
Outline matrix multi OS build usage in README

### ISSUE THREAD

**Issue by kwin** [EnricoMi/publish-unit-test-result-action#626]
As using EnricoMi/publish-unit-test-result-action/composite@v2 is [deprecated](https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#running-as-a-composite-action) I am wondering how to best collect test report in a matrix build covering multiple operating systems. 
In those cases you usually share the same steps among all builds, however different OSes require now different steps.

**Comment by kwin** [comment]
Is there some way to derive the step name from the workflow_label (https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners) usually used in the matrix variable and in https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on.

**Comment by EnricoMi** [comment]
You do not need to run the publish action on the same operating system as your tests. Simply move the publish action out of your test job into a subsequent job. The test jobs upload test results as artifacts and a single test result publish job processes all test result files.

**Comment by kwin** [comment]
Thanks, I now see it being there already: https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#use-with-matrix-strategy. Sorry for the noise then.
