### ISSUE TITLE
Emoji not rendered

### ISSUE THREAD

**Issue by sebastien-savalle** [EnricoMi/publish-unit-test-result-action#628]
We recently noticed a strange behavior with emoji included in the report. They are no longer rendered, except the duration

One example:
<img width="373" alt="image" src="https://github.com/user-attachments/assets/25c9ec62-19d3-4081-92da-9d421c9f4043">

Could you have a look ?
Thanks a lot,
Sebastien

**Comment by EnricoMi** [comment]
Is that on an enterprise github (non-public)? Do checks not render or job summaries or pull request comments?

**Comment by EnricoMi** [comment]
I presume that is an enterprise github setup issue because the markdown is rendered by Github UI. I presume a config change has happened.

**Comment by EnricoMi** [comment]
Looks like the dorny report uses the unicode character: https://github.com/dorny/test-reporter/blob/1a288b62f8b75c0f433cbfdbc2e4800fbae50bd7/src/utils/markdown-utils.ts#L8-L12

**Comment by EnricoMi** [comment]
I could not find any announcement by Github that those named emoji might be deprecated, only this bug report that got resolved: https://github.com/orgs/community/discussions/77606

**Comment by EnricoMi** [comment]
Interesting is that the named stopwatch emoji :stopwatch: is working for you...

**Comment by sebastien-savalle** [comment]
> I presume ✅ is a unicode character in that markdown and not a ✅ (`:white_check_mark:`)?
> 
> Please try the following: copy the following lines into a message in your enterprise github:
> 
> ```
> ✅ is a unicode character
> :white_check_mark: needs to be rendered
> ```

![image](https://github.com/user-attachments/assets/76a56abc-c7d5-40b2-8913-31bda28b0246)


And we use it (`:white_check_mark:`) regularly in pull request without issues

**Comment by sebastien-savalle** [comment]
You're right, the other action seems to use unicode icons. 

https://github.com/dorny/test-reporter/blob/1a288b62f8b75c0f433cbfdbc2e4800fbae50bd7/src/utils/markdown-utils.ts#L9

**Comment by sebastien-savalle** [comment]
Sure

```
## Backend Tests Result
   15 files    864 suites   31m 13s :stopwatch:
3 734 tests 3 730 :white_check_mark: 4 :zzz: 0 :x:
3 768 runs  3 764 :white_check_mark: 4 :zzz: 0 :x:

Results for commit 5a770bff.

[test-results]:data:application/gzip;base64,H4sIANOBB2cC/02PQQ6DIBBFr2JYdzEgMtrLNIiQkKo0CCvTu3dEG1y+9ycvsDPnZ7uxZ8O7R8O27FOhXknCKUedfFiPuceWDK3p2Fts5R9fWzbmdFDd23/I1SOn/UyiXtgYQ7xMzOtZVf1FNVpecqraLHxLFr4XTVgWnwhYpxFhdA4QpBhRm0kAiEEqBZo+Zbg1E8eBs+8PC0H2RA0BAAA=

:recycle: This comment has been updated with latest results.
```

**Comment by EnricoMi** [comment]
Can you edit the pull request comment once more and add
```
✅ is a unicode character
:white_check_mark: needs to be rendered
```
from above to it and see if that renders as before?

**Comment by EnricoMi** [comment]
Can you try running the action from this branch to test a fix?

    uses: EnricoMi/publish-unit-test-result-action/composite@unicode-emojis

That branch uses unicode emojis rather than markdown.

**Comment by sebastien-savalle** [comment]
This is clearly better :)

I used
uses: EnricoMi/publish-unit-test-result-action@unicode-emojis
not 
uses: EnricoMi/publish-unit-test-result-action/composite@unicode-emojis

<img width="518" alt="image" src="https://github.com/user-attachments/assets/1459e8c9-85fd-40fc-947a-e0a0152261a8">

**Comment by EnricoMi** [comment]
With `uses: EnricoMi/publish-unit-test-result-action@unicode-emojis` you effectively run the release version, not the changes of the `unicode-emojis` branch. If you edit the comment, you should see it contains markdown emojis. Interesting that this works again.

**Comment by sebastien-savalle** [comment]
I can confirm this is markdown, sometimes it works, sometimes not. Really weird.

**Comment by EnricoMi** [comment]
That is why I would like you to test this branch to see if this works around this bug. In the end Github has to fix it but I'd prefer the unicode emojis if they make things more robust.

**Comment by sebastien-savalle** [comment]
Yes I understood but I can't use the composite action which is not approved by my github enterprise.

**Comment by EnricoMi** [comment]
Alright, I think this is safe to be released.

**Comment by EnricoMi** [comment]
Fix has been released.
