### ISSUE TITLE
Unable to use Action on Self-Hosted Windows Runner with `powershell` shell

### ISSUE THREAD

**Issue by sesa623061** [EnricoMi/publish-unit-test-result-action#634]
We are trying using the Windows version of action to publish unit tests, but we are getting below error as mentioned in the screen shot.
![image](https://github.com/user-attachments/assets/55b3fff5-b73e-4e2d-9fb1-aebbcb81bcfa)

Below is the task which we have added in the yml file.

    - name: Setup Python
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3
      with:
        python-version: '3.10'

    - name: Publish unit tests results
      uses: EnricoMi/publish-unit-test-result-action/windows@30eadd5010312f995f0d3b3cff7fe2984f69409e
      if: always() && ${{ (inputs.unittests) || (github.event_name == 'pull_request') }}
      with:
        files: |
          ${{ github.workspace }}/src/TestResults.xml
          ${{ github.workspace }}/src/CoverageReport/Cobertura.xml
          ${{ github.workspace }}/src/OpenCover.xml

**Comment by EnricoMi** [comment]
Looks like you do not have PowerShell (`pwsh`) installed.

**Comment by sesa623061** [comment]
Thannks for your reply @EnricoMi , I have Powershell installed already in my machine and same is updated at environment variables also.
![image](https://github.com/user-attachments/assets/7aa128bb-8c19-4b52-a7fd-bc7f4d92ffe7)

**Comment by sesa623061** [comment]
and most of my steps inside workflow runs using **shell: powershell** only

**Comment by EnricoMi** [comment]
Looks like PowerShell v5 provides powershell.exe whereas PowerShell v6 and v7 provide pwsh.exe.

**Comment by EnricoMi** [comment]
Can you test the following please:

    uses: EnricoMi/publish-unit-test-result-action/windows/powershell@windows-powershell

**Comment by sesa623061** [comment]
This action is tag is not allowed in my enterprise organization. but let me download the action manually and test once please.

**Comment by sesa623061** [comment]
@EnricoMi , I dont find any action/sub folder for powershell under windows folder in the code. Can i still use the action as you mentioned?
![image](https://github.com/user-attachments/assets/4f45567e-4828-46d0-b215-ebe5b5f84e93)

**uses: EnricoMi/publish-unit-test-result-action/windows/powershell@windows-powershell**

**Comment by EnricoMi** [comment]
Check out branch `windows-powershell`, there is `windows/powershell`.

**Comment by sesa623061** [comment]
I have tried this - uses: EnricoMi/publish-unit-test-result-action/windows/powershell@windows-powershell
but I am getting this error every time. Module not found for 3.8, 3.10 & 3.12 versions of python.
![image](https://github.com/user-attachments/assets/a362128a-bef7-464f-8ae4-ea5bd532e938)

**Comment by EnricoMi** [comment]
Looks like `powershell` has a different syntax than `pwsh`. I would need to setup a `powershell` environment to migrate and test the `pwsh` script.

**Comment by sesa623061** [comment]
Thank you @EnricoMi, I have upgraded my powershell to v7 and now i can able to use the action and it seems working fine with v7. But few of the file formats are accepting it seems.
Below is the output summary of  action with **TestResults.xml**


Is **OpenCover.xml & Cobertura.xml** are accepted formats in this action?

ERROR LOG:
![image](https://github.com/user-attachments/assets/d928f560-ae79-418e-a399-3056561f747a)

**Comment by EnricoMi** [comment]
Sounds like those file contain test coverage information, which are not test result information.

**Comment by sesa623061** [comment]
yes @EnricoMi , we have coverage information in it. do we have any plan to create an action to support coverage as well please?

**Comment by EnricoMi** [comment]
Adding coverage sounds like a natural fit for this action. But I have not looked into this. Happy to review pull requests on this area.

**Comment by EnricoMi** [comment]
I have created issues #640 and #639 to track these new features. Please reopen if there are any further issues.
