### ISSUE TITLE
Status message on Github Action Summary Page not correct

### ISSUE THREAD

**Issue by yhrabovskyinomi** [EnricoMi/publish-unit-test-result-action#68]
Hello, I am using karma tests for my project with junit reporter to create .xml reports.
When I am parsing this xml with this GitHub actions all looks pretty cool except this Summary Page. For some reason I can see same name for all failed test.
![image](https://user-images.githubusercontent.com/71638755/102884594-8986f280-445a-11eb-981c-24435d7eb872.png)

I've found this topic: https://github.com/EnricoMi/publish-unit-test-result-action/issues/34 but didn't find any way to solve the problem on karma side :( 

Also I've tried some others actions: scacap/action-surefire-report@v1, ashley-taylor/junit-report-annotations-action@1.3 and all of them managed to get this Summary page looks good. 

So probably problem somewhere in this action.

Would appreciate any help.

Thanks

**Comment by EnricoMi** [comment]
Thanks for raising this. Is that repo public? Can you link me to the check runs for my and the other actions?

**Comment by EnricoMi** [comment]
Or can you provide me with the unit test result xml files so I can reproduce it?

**Comment by yhrabovskyinomi** [comment]
Private repo, but I've attached xml example

[karma-test-results.xml.zip](https://github.com/EnricoMi/publish-unit-test-result-action/files/5730802/karma-test-results.xml.zip)

**Comment by EnricoMi** [comment]
So this is about the summary page, where GitHub summarizes all annotations. It takes the multi-line message of each annotation and turns it into a single line. I think the title of each annotation would be a better pick for that one line (that one contains the test class and name). But I think there is nothing I can do about that decision.

Can you provide screenshots of the other actions' annotations summary and their annotations page? Their annotations seem to be better suited for GitHub's way of summarizing them.

**Comment by yhrabovskyinomi** [comment]
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/71638755/102915347-54929400-448a-11eb-96a0-fb31bbaac4d9.png">

**Comment by yhrabovskyinomi** [comment]
this is for scacap/action-surefire-report@v1

**Comment by EnricoMi** [comment]
Thanks! And when you click on the `core-test#L1` link on the right you will get to the actual annotation. How does that look like?

**Comment by yhrabovskyinomi** [comment]
When I am clicking it, it redirecting me to commit of this actions change. So I would say link not working as expected but at least I can see failed test cases 
<img width="855" alt="image" src="https://user-images.githubusercontent.com/71638755/102917714-5bbba100-448e-11eb-91de-af80a93395cf.png">

**Comment by yhrabovskyinomi** [comment]
All of links in annotations moves me to commit of this workflow build.

**Comment by EnricoMi** [comment]
Sorry, you are right. There does not seem to be a way to get from the Summary of annotations to the actual annotations. This is annoying.

For this action, the check run generated by the action lists all annotations: https://github.com/EnricoMi/python/runs/1142716011?check_suite_focus=true

![annotations](https://user-images.githubusercontent.com/44700269/102918378-15af0f00-4487-11eb-87a0-8d1bfe7ef13c.png)

The title of the annotations would look great on the Summary page.

How is this as a summary / overview? There must be something similar for other actions as well.

**Comment by yhrabovskyinomi** [comment]
Title the one with yellow? ye, should be good

**Comment by EnricoMi** [comment]
So you agree the way GitHub summarizes these annotations is rubbish and the list of annotations in the Check run created by the action suffices as a summary? Or is there anything else you suggest I could do to improve things?

**Comment by yhrabovskyinomi** [comment]
I mean would be good to see at least test case title (bold yellow on my screenshot)
```
app.test.core-test sidebar-percentage-values-25 (Chrome_Headless_87_0_4280_88_(Linux_x86_64).app.test.core-test) failed
```
And not same .xml file path for all occurrence
```
test/Chrome_Headless_87.0.4280.88_(Linux_x86_64)/test/karma-test-results.xml
```

But I do not have any knowledge about how GitHub Actions handling this Summary Anotations, so this question up to you. 
If you can not see how to improve this, then you are free to close this issue. I can live without it :)


![image](https://user-images.githubusercontent.com/71638755/103227685-9f535680-4937-11eb-8709-fd543d860d9c.png)

**Comment by EnricoMi** [comment]
There is no way to get the annotation title (bold yellow) into the annotation summary (which picks the annotation message, the gray monospace multi-line content). Sorry, I hope, GitHub is going to improve that.

I think the annotations (title and message) are good the way they are, especially when you have multiple runs per test. I could move the title into the message as only the message is required and title is optional, but this feels like working around the Github issue and not making use of the annotation structure. So I am closing this. Thanks for the insights though!
