### ISSUE TITLE
Distinguish between golang test and subtests

### ISSUE THREAD

**Issue by rogeriopeixotocx** [EnricoMi/publish-unit-test-result-action#78]
Golang's [table-driven tests](https://github.com/golang/go/wiki/TableDrivenTests) used along with [go-junit-report](https://github.com/jstemmer/go-junit-report) generates JUnit files such as this.

```
	<testsuite tests="28" failures="0" time="0.031" name="github.com/Checkmarx/kics/pkg/engine">
		<properties>
			<property name="go.version" value="go version go1.15.6 linux/amd64"></property>
			<property name="coverage.statements.pct" value="35.1"></property>
		</properties>
		<testcase classname="engine" name="TestMapKeyToString" time="0.000"></testcase>
		<testcase classname="engine" name="TestMapKeyToString/mapKeyToString-0" time="0.000"></testcase>
		<testcase classname="engine" name="TestMapKeyToString/mapKeyToString-1" time="0.000"></testcase>
		<testcase classname="engine" name="TestMapKeyToString/mapKeyToString-2" time="0.000"></testcase>
		<testcase classname="engine" name="TestMapKeyToString/mapKeyToString-3" time="0.000"></testcase>
		<testcase classname="engine" name="TestMapKeyToString/mapKeyToString-4" time="0.000"></testcase>
		<testcase classname="engine" name="TestComputeSimilarityID" time="0.000"></testcase>
		<testcase classname="engine" name="TestComputeSimilarityID/Changed_file_name" time="0.000"></testcase>
		<testcase classname="engine" name="TestComputeSimilarityID/Changed_queryID" time="0.000"></testcase>
		<testcase classname="engine" name="TestComputeSimilarityID/Changed_searchKey" time="0.000"></testcase>
		<testcase classname="engine" name="TestComputeSimilarityID/Changed_filepath_dir" time="0.000"></testcase>
		<testcase classname="engine" name="TestComputeSimilarityID/No_changes" time="0.000"></testcase>
		<testcase classname="engine" name="TestComputeSimilarityID/Relative_directory_resolution" time="0.000"></testcase>
		<testcase classname="engine" name="TestComputeSimilarityID/No_changes,_empty_searchValue" time="0.000"></testcase>
		<testcase classname="engine" name="TestStandardizeFilePathEquals" time="0.000"></testcase>
		<testcase classname="engine" name="TestStandardizeFilePathEquals/Clean_input" time="0.000"></testcase>
		<testcase classname="engine" name="TestStandardizeFilePathEquals/Cleanup_double_slashes" time="0.000"></testcase>
```
Currently, the comment shows a very high number of unit tests, because of the subtests:
![image](https://user-images.githubusercontent.com/75368139/105704478-c5542280-5f06-11eb-81b0-f6423efe9231.png)

It would be great if we could have a configuration setup to differentiate the tests (e.g: `TestMapKeyToString`) from subtests (e.g: `TestMapKeyToString/mapKeyToString-0`) and count them separately in the PR comments.

**Comment by EnricoMi** [comment]
This looks like a very specific behaviour of your test runner. One could argue, each parameter is a test on its own, so counting them as individual tests is fine. Table driven testing naturally results in a high number of tests.

Alternatively, there is the notion of test runs and you could count each parameter value towards a test run. But then this collides with the actual notion of test runs where tests run in different environments, which you could still have with your table driven tests.

Introducing subtests would also have to incorporated into reporting test addition, test deletion and test skipping / un-skipping.

Not sure if adding the notion of subtests in addition to runs is worth the effort. However, contributions welcome!

**Comment by EnricoMi** [comment]
Closing this, happy to re-open for contribution.

**Comment by rogeriopeixotocx** [comment]
Thanks @EnricoMi I want to contribute to this, I just need to find a little time.
