### ISSUE TITLE
Configuration to provide URL to bot's avatar image in comments

### ISSUE THREAD

**Issue by rogeriopeixotocx** [EnricoMi/publish-unit-test-result-action#79]
It would be great to be able to configure an URL or path pointing to an image, that would be the profile picture of the github bot that posts the comments in the PR.

**Comment by EnricoMi** [comment]
That would be a great way to customize the action. Comments are created through the [GitHub REST API](https://docs.github.com/en/rest/reference/issues#create-an-issue-comment). This requires either a GitHub App token, or a [Personal Access Token (PAT)](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token). The identity of the comment author is determined by that token.

Currently, the GitHub Actions app's token is used, which results in this image:
![grafik](https://user-images.githubusercontent.com/44700269/105993356-9a083980-60a6-11eb-803d-23166c920050.png)

With a PAT (currently not supported by this action), that user's image would be used (see #80):
![grafik](https://user-images.githubusercontent.com/44700269/105993522-d0de4f80-60a6-11eb-8bc8-49d23e23babd.png)

But I cannot see a way to modify that image for a specific PAT. I think that would be a nice feature for the GitHub Actions app.
